- 3.distributed-calculator/README.md
.NET Core app is doing subtraction and Python app is doing multiplication, but it's opposite in the docs.
> Fixed Subtraction and Multiplication docs

- 3.distributed-calculator/README.md
> Fix mispelling

- 5.bindings/README.md
> Fix misspelling

- 2.hello-kubernetes/README.md
fixed wording in 2-hello-kuberentes README.md
> fix wording

- 2.hello-kubernetes/README.md
> fix missing a point

- .github/pull_request_template.md
Tweaked the checklist, since sample PRs are different from runtime PRs.
> Updated Sample PR guidelines

- README.md
Add sample versioning with runtime
#81 
> Add sample versioning with runtime

- README.md
Add build and license badges
#80 
> Add build and license badges

- README.md
Reorder Supported Dapr Runtime version section (requested by @msfussell )
#81 
> Reorder Supported Dapr Runtime version section

- README.md
Use badge for the build from master branch
N/A
> Use badge for the build from master branch

- 5.bindings/README.md
Adding the command for removing the local Kafka Docker Container
> Cleanup for running 5. bindings locally

- 1.hello-world/README.md
Added clarification about port configurability to make it clear that the app could run on a port other than 3000.
This clarification closes #100
> Added clarification about port configurability

- 5.bindings/README.md
- 5.bindings/deploy/kafka_bindings.yaml
- 5.bindings/nodeapp/components/kafka_bindings.yaml
- 5.bindings/pythonapp/components/kafka_bindings.yaml
> update Kafka binding with authRequired

- 2.hello-kubernetes/README.md
Fixed broken link in 2.hello-kubernetes. Did not find another broken link in this file.
Please reference the issue this PR will close: #109
> Fixing broken link in 2.hello-kubernetes

- 1.hello-world/README.md
Update README.md for 1.hello-world to reflect latest version.
Please reference the issue this PR will close: #90
> Update README.md for 1.hello-world

- 4.pub-sub/README.md
> Fix sample typo

- 2.hello-kubernetes/README.md
Use `or` instead of `and` to show that list of Kubernetes cluster options are not exhaustive.
> Update prerequisites wording in README.md to be less explicit

- 1.hello-world/README.md
The Windows Dapr CLI send command was wrong
> Fixed the quotes for dapr send on windows

- 2.hello-kubernetes/README.md
Signed-off-by: Lachlan Evenson <lachlan.evenson@microsoft.com>
Two quick fix typos in the Kubernetes installation docs
No issue ref
> (fix/docs): Update sample app install instructions

- 2.hello-kubernetes/README.md
Updated readme to reflect the new location of the app.py code that is referenced
> Updated readme

- 5.bindings/README.md
Upgrade from helm2 to helm3
N/A
> Upgrade from helm v2 to helm v3

- 3.distributed-calculator/deploy/dotnet-subtractor.yaml
- 3.distributed-calculator/deploy/go-adder.yaml
- 3.distributed-calculator/deploy/node-divider.yaml
- 3.distributed-calculator/deploy/python-multiplier.yaml
- 3.distributed-calculator/deploy/react-calculator.yaml
- 4.pub-sub/deploy/node-subscriber.yaml
- 4.pub-sub/deploy/python-subscriber.yaml
- 4.pub-sub/deploy/react-form.yaml
- 5.bindings/deploy/node.yaml
- 5.bindings/deploy/python.yaml
- 7.middleware/deploy/echoapp.yaml
* Added tags to all sample images in deploy yamls
[Link to the issue](https://github.com/dapr/samples/issues/145)
Please reference the issue this PR will close: #_[145]_
> Add tags to all sample images in deploy yamls

- 2.hello-kubernetes/README.md
A few clarifications to the instructions for Hello Kubernetes sample. 
#136 
* [x ] You've updated the sample's README if necessary
> Clarify sample instructions

- README.md
Add 0.4.0 dapr runtime version links
N/A
> Add 0.4.0 dapr runtime version links [DO-NOT-MERGE]

- 2.hello-kubernetes/deploy/node.yaml
- 2.hello-kubernetes/deploy/python.yaml
- 3.distributed-calculator/deploy/dotnet-subtractor.yaml
- 3.distributed-calculator/deploy/go-adder.yaml
- 3.distributed-calculator/deploy/node-divider.yaml
- 3.distributed-calculator/deploy/python-multiplier.yaml
- 3.distributed-calculator/deploy/react-calculator.yaml
- 4.pub-sub/deploy/node-subscriber.yaml
- 4.pub-sub/deploy/python-subscriber.yaml
- 4.pub-sub/deploy/react-form.yaml
- 5.bindings/deploy/node.yaml
- 5.bindings/deploy/python.yaml
- 6.functions-and-keda/setup.ps1
- 7.middleware/deploy/echoapp.yaml
Updated image tags to `edge` for all samples
N/A - doing this as part of release process
> Update docker image tags to edge per release process

- 5.bindings/pythonapp/app.py
Fix sample5 output for python app.
Please reference the issue this PR will close: #167 
> Fix sample5 output for python app.

- README.md
> Add 0.5.0 version note

- 2.hello-kubernetes/README.md
Fixing the python app path for hello-kubernetes sample.
> Fixing the python app path for hello-kubernetes sample

- 2.hello-kubernetes/deploy/node.yaml
- 2.hello-kubernetes/deploy/python.yaml
- 3.distributed-calculator/deploy/dotnet-subtractor.yaml
- 3.distributed-calculator/deploy/go-adder.yaml
- 3.distributed-calculator/deploy/node-divider.yaml
- 3.distributed-calculator/deploy/python-multiplier.yaml
- 3.distributed-calculator/deploy/react-calculator.yaml
- 4.pub-sub/deploy/node-subscriber.yaml
- 4.pub-sub/deploy/python-subscriber.yaml
- 4.pub-sub/deploy/react-form.yaml
- 5.bindings/deploy/node.yaml
- 5.bindings/deploy/python.yaml
- 7.middleware/deploy/echoapp.yaml
Updated image tags to release version 0.6.0
This is as part of release process
> Update image tags to release version 0.6.0

- README.md
Updating 0.6.0 version in Readme
Part of release process.
> Updating 0.6.0 version in Readme

- 2.hello-kubernetes/deploy/node.yaml
- 2.hello-kubernetes/deploy/python.yaml
- 3.distributed-calculator/deploy/dotnet-subtractor.yaml
- 3.distributed-calculator/deploy/go-adder.yaml
- 3.distributed-calculator/deploy/node-divider.yaml
- 3.distributed-calculator/deploy/python-multiplier.yaml
- 3.distributed-calculator/deploy/react-calculator.yaml
- 4.pub-sub/deploy/node-subscriber.yaml
- 4.pub-sub/deploy/python-subscriber.yaml
- 4.pub-sub/deploy/react-form.yaml
- 5.bindings/deploy/node.yaml
- 5.bindings/deploy/python.yaml
- 7.middleware/deploy/echoapp.yaml
Changed image versions back to edge
This is part of release process as of 0.6.0
> Change image versions back to edge

- 6.functions-and-keda/README.md
Assumption is that the user has already cd'ed to the correct directory, this is inconsistent with the other samples.
Added a cd 6.functions-and-keda to the instructions.
None. minor change for consistency.
> add cd line

- 1.hello-world/README.md
- Clarifying components directory auto creation.
- Adding more next steps.
- Additional minor clarifications.
- Spacing for easier command copy/paste
Closes https://github.com/dapr/samples/issues/189 
> Clarifications for 1.hello-world sample

- 1.hello-world/README.md
Prerequisite states use of Python3 (python users should be familiar enough to know how to change to Python 2.x if they really want to)
> Simplifying Python commands

- 8.observability/README.md
- 8.observability/deploy/appconfig.yaml
https://github.com/dapr/docs/issues/550
> Update tracing configuration in the sample

- README.md
Add link to the 0.7.0 runtime as part of release process
N/A
> Add link to the 0.7.0 runtime as part of release process

- 3.distributed-calculator/csharp/Controllers/SubtractController.cs
- 3.distributed-calculator/csharp/Dockerfile
- 3.distributed-calculator/csharp/Program.cs
- 3.distributed-calculator/csharp/Properties/launchSettings.json
- 3.distributed-calculator/csharp/Startup.cs
- 3.distributed-calculator/csharp/Subtract.csproj
Upgrading to `netcoreapp3.1` see #155 
> Updating csharp distributed calculator to .NET Core 3.1

- 4.pub-sub/README.md
- 4.pub-sub/node-subscriber/app.js
- 4.pub-sub/python-subscriber/app.py
> Update pub/sub subscriptions

- 3.distributed-calculator/README.md
- 3.distributed-calculator/csharp/Controllers/SubtractController.cs
… (#184)
- Add console logging to subtract app
> - Add instructions for running the distributed calculator app locally (#184

- 6.functions-and-keda/setup.ps1
1) Remove syntaxis errors. Adding { } to 10 variables in the script.
2) Using helm to install keda.
Please reference the issue this PR will close: # it refers to here if we use the command func kubernetes https://github.com/Azure/azure-functions-core-tools/issues/1883
> Changing ps1 script in demo 6.

- 3.distributed-calculator/README.md
> Add instructions to run Sample3 locally - Second round of review comments

- 2.hello-kubernetes/README.md
> Fix readme links (#213)

- 2.hello-kubernetes/README.md
- 9.secretstore/README.md
- 9.secretstore/deploy/node.yaml
- 9.secretstore/makefile
- 9.secretstore/node/.gitignore
- 9.secretstore/node/Dockerfile
- 9.secretstore/node/app.js
- 9.secretstore/node/package.json
- README.md
> Secret Store Sample (#175)

- 1.hello-world/app.py
- 2.hello-kubernetes/python/app.py
Add timeout to Python requests to fix #218
#218
> Add timeout to HTTP requests in Python samples

- 9.secretstore/README.md
Added links and cosmetic changes to samples README
(these changes were reverted during the initial PR process)
> Updating secret store sample instructions

- 1.hello-world/app.py
- 2.hello-kubernetes/python/app.py
- 5.bindings/pythonapp/app.py
Flush logs in the Python App, so that they become visible even in non-interactive sessions like when running within a container.
#220 
> Flush Python logs to display them in non-interactive sessions

- 5.bindings/README.md
- 5.bindings/pythonapp/app.py
Updates the output binding code to match the new payload JSON schema for `0.8.0`.
> Update bi-directional bindings request

- 3.distributed-calculator/README.md
Small cosmetic change to fix broken link markdown
> Small fix to pre-req link text

- 4.pub-sub/README.md
Changed --payload to --data for pub-sub sample
> Change --payload to --data for pub-sub sample

- README.md
Updated README with link to dapr 0.8.0 as per release process
> Update README with link to dapr 0.8.0

- README.md
Updated README with new Docker Compose sample
As part of release
> Update README with new sample

- 1.hello-world/README.md
Added a link to a known issue - running python with dapr on windows
Please reference the issue this PR will close: #240 
> Link python setup issue in sample 1

- .github/workflows/build.yml
Add secretstore sample to workflow
Please reference the issue this PR will close: #257 
* [] The sample code compiles correctly
> Add secretstore sample to workflow

- 9.secretstore/deploy/node.yaml
Fix image name to reflect the pushed image.
Please reference the issue this PR will close: #257 
> Fix naming of secretstore image

- 10.hello-docker-compose/README.md
- 7.middleware/README.md
Fix middleware sample README
Please reference the issue this PR will close: It's a small issue, n o issue was created
> Fix middleware sample README

- .github/workflows/build.yml
Added 10.hello-docker-compose to build workflow
Please reference the issue this PR will close: small change so haven't created issue
> Add 10.hello-docker-compose to build workflow

- .github/workflows/build.yml
sample 10 doesn't have the image to be uploaded.
Reverts dapr/samples#263
> Revert "Add 10.hello-docker-compose to build workflow"

- README.md
Added 0.9.0 to version table
Please reference the issue this PR will close: changes needed as per release process
> Add 0.9.0 to version table

- 1.hello-world/README.md
- 10.hello-docker-compose/README.md
- 10.hello-docker-compose/docker-compose.yml
- 11.hello-dapr-slim/README.md
- 2.hello-kubernetes/README.md
- 2.hello-kubernetes/deploy/node.yaml
- 2.hello-kubernetes/deploy/python.yaml
- 3.distributed-calculator/README.md
- 3.distributed-calculator/deploy/dotnet-subtractor.yaml
- 3.distributed-calculator/deploy/go-adder.yaml
- 3.distributed-calculator/deploy/node-divider.yaml
- 3.distributed-calculator/deploy/python-multiplier.yaml
- 3.distributed-calculator/deploy/react-calculator.yaml
- 4.pub-sub/README.md
- 4.pub-sub/deploy/node-subscriber.yaml
- 4.pub-sub/deploy/python-subscriber.yaml
- 4.pub-sub/deploy/react-form.yaml
- 5.bindings/deploy/node.yaml
- 5.bindings/deploy/python.yaml
- 6.functions-and-keda/deploy/csharp-function-subscriber.yaml
- 6.functions-and-keda/deploy/javascript-function-subscriber.yaml
- 6.functions-and-keda/deploy/python-function-publisher.yaml
- 6.functions-and-keda/utils/base-templates/csharp-function-subscriber-base.yaml
- 6.functions-and-keda/utils/base-templates/javascript-function-subscriber-base.yaml
- 6.functions-and-keda/utils/base-templates/python-function-publisher-base.yaml
- 7.middleware/deploy/echoapp.yaml
- 8.observability/deploy/python-multiplier.yaml
- 9.secretstore/deploy/node.yaml
Replaced deprecated cli options and k8s annotations with new ones
Please reference the issue this PR will close: #267 
> Replace deprecated cli options and k8s annotations

- middleware/README.md
Added guidance for adding the correct helm chart repository. This is a follow up PR for closed #275.
Please reference the issue this PR will close: #274
* [N.A.] The quickstart code compiles correctly
> Clarify ingress helm install hint

- README.md
- bindings/README.md
- distributed-calculator/README.md
- hello-kubernetes/README.md
- hello-world/README.md
- middleware/README.md
- observability/README.md
- pub-sub/README.md
- secretstore/README.md
This PR makes adjustments to style and tone of quickstart tutorials as well as ensuring users can easily use the repo and a next step is defined for every quickstart
Closes https://github.com/dapr/quickstarts/issues/280 
> Updating quickstart READMEs

- pub-sub/README.md
- pub-sub/deploy/redis.yaml
- pub-sub/node-subscriber/app.js
- pub-sub/python-subscriber/app.py
- pub-sub/react-form/server.js
Modified sample to work with multi pubsub changes
Please reference the issue this PR will close: #286 
> Modify sample to work with multi pubsub changes

- pub-sub/README.md
> Fixes python-subscriber dir name

- distributed-calculator/react-calculator/client/package-lock.json
- distributed-calculator/react-calculator/client/package.json
Fix vulnerabilities in react frontend client dependencies
Please reference the issue this PR will close: #298 
> Fix vulnerabilities in react frontend client dependencies

- secretstore/README.md
- secretstore/deploy/node.yaml
- secretstore/node/app.js
- secretstore/node/components/local-secret-store.yaml
- secretstore/node/secrets.json
Add local secret store quickstart. 
Modified application to be portable between Kubernetes and local machine.
Please reference the issue this PR will close: #287 
> Add local secret store quickstart

- secretstore/README.md
Update text in the secret readme sample to include the new env variable secret store
> readme update

- README.md
Adds link to the examples in go sdk repo
> adds link to go sdk examples

- pub-sub/README.md
Use `kubectl --selector` to simplify PubSub sample
> Use kubectl selector to simplify PubSub sample

- secretstore/README.md
Fix formatting in secret store quickstart sample
> Fix formatting in secret store quickstart sample

- .github/scripts/get_release_version.py
- .github/workflows/build.yml
Remove set-env due to CVE-2020-15228
Please reference the issue this PR will close: Part of https://github.com/dapr/dapr/issues/2202 
> Remove set-env due to CVE-2020-15228

- .gitignore
- bindings/README.md
- bindings/nodeapp/package.json
- hello-world/package.json
- pub-sub/README.md
- pub-sub/react-form/client/yarn.lock
* sec-related updates to node example deps 
* pip3 and python3 sync 
* add .gitignore to ignore `package-lock.json` globally 
> qd local mode rc review patches

- bindings/README.md
- bindings/kafka-non-persistence.yaml
The incubations/kafka helm chart has been deprecated. Update 
Please reference the issue this PR will close: #325
> Update documentation to use a working helm chart (#325)

- README.md
Update README for v1.0.0-rc.1
Please reference the issue this PR will close: End game
> Update README for v1.0.0-rc.1

- observability/README.md
Update dapr configuration output.
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/487
> Update dapr configuration output.

- hello-world/README.md
For the changes made in CLI.
Please reference the issue this PR will close: https://github.com/dapr/quickstarts/issues/332
> change invoke payload to data flag

- middleware/deploy/pipeline.yaml
> update tracing config fields

- observability/README.md
Update observability quickstart to include local instruction
Please reference the issue this PR will close: #288 
> Update observability quickstart to include local instruction

- README.md
Update runtime version table for 1.0.0-rc2
> Update README.md for 1.0.0-rc2

- README.md
Merge release-1.0 branch to master
> Merge release-1.0 branch to master

- .github/workflows/validate.yaml
- distributed-calculator/README.md
- distributed-calculator/makefile
- hello-world/README.md
- hello-world/makefile
- validate.mk
I have added autovalidation annotations to hello-world and distributed-calculator. This will allow us to automatically run the steps contained in our build validation 
refs: #357
There will be more PRs coming for other quickstarts.
> Add autovalidation annotations to hello-world and distributed-calculator

- .github/workflows/validate.yaml
- pub-sub/README.md
- pub-sub/makefile
- pub-sub/python-subscriber/app.py
The pubsub quickstart local (non-k8s) instructions are now autovalidating.
Please reference the issue this PR will refs: #357
> Adding auto validation to pub-sub example (Part of #357)

- .github/workflows/validate.yaml
- bindings/README.md
- bindings/makefile
- secretstore/README.md
- secretstore/makefile
- secretstore/node/app.js
Added autovalidation steps for secretstore and bindings quickstarts. This completes autovalidation for all the locally run quickstarts. 
refs: #357 
> Adding auto validation to bindings and secrestore example (Part of #357)

- .github/workflows/validate.yaml
- distributed-calculator/README.md
- hello-kubernetes/README.md
- hello-kubernetes/makefile
Adding a KinD cluster and automating the validation of our kubernetes steps. 
Please reference the issue this PR will close: #357
> Add kubernetes to automated validation

- .github/workflows/validate.yaml
- bindings/README.md
Add automation for the Kubernetes portion of the binding quickstarts.
Please reference the issue this PR will close: #357
> Automate validation of bindings steps for kubernetes (#357)

- bindings/README.md
- bindings/deploy/kafka_bindings.yaml
- bindings/nodeapp/components/kafka_bindings.yaml
- bindings/nodeapp/components/redis.yaml
- bindings/nodeapp/components/redis_messagebus.yaml
- bindings/pythonapp/components/kafka_bindings.yaml
- bindings/pythonapp/components/redis.yaml
- bindings/pythonapp/components/redis_messagebus.yaml
- distributed-calculator/deploy/redis.yaml
- hello-kubernetes/deploy/redis.yaml
- hello-world/README.md
- middleware/deploy/oauth2.yaml
- pub-sub/deploy/redis.yaml
- secretstore/README.md
- secretstore/node/components/local-secret-store.yaml
> add version field to components

- .github/workflows/validate.yaml
- observability/README.md
- observability/makefile
Clarification added to the observability quickstart. Also, automated the self hosted version.
> Add automatic validation to observability quickstart

- .github/workflows/validate.yaml
- observability/README.md
Also added validation steps for observability in Kubernetes.
> Add kubernetes validation to observability quickstart

- observability/README.md
Improve reproducibility of observability demo.
Please reference the issue this PR will close: endgame
> Improve reproducibility of observability demo.

- middleware/README.md
Improve middleware quickstart.
Please reference the issue this PR will close: endgame
> Improve middleware quickstart.

- .github/workflows/validate.yaml
- README.md
Update release table for runtime 1.0.0
> Update for release

- README.md
Fixes broken links in README.md for .NET SDK
> Fix broken links for .NET SDK

- .github/workflows/validate.yaml
- README.md
- makefile
Turn on broken link detection for root README.md
> Enable linkcheck readme

- pub-sub/README.md
This fixes links that are leading to the Chinese docs version instead of the  English version
Closes https://github.com/dapr/quickstarts/issues/410 
> Fixing links

- .github/workflows/validate.yaml
- hello-world/package-lock.json
- observability/README.md
Updating the runtime for quickstart validation.
> Runtime to 1.1.0-rc.2

- .github/workflows/validate.yaml
- README.md
> Update quickstarts for 1.1.0 release

- .github/workflows/validate.yaml
> Update runtime version to 1.1.1

- .github/workflows/validate.yaml
- observability/README.md
Update to latest runtime and validate.
> Bump runtime to 1.2.0-rc.3

- .github/workflows/validate.yaml
> Runtime version to 1.2.0-rc.4

- .github/workflows/validate.yaml
> Runtime version to 1.2.0-rc.5

- .github/workflows/validate.yaml
- README.md
> Bump for runtime release 1.2.0

- hello-kubernetes/README.md
cluser changed to cluster
Just fixed a typo
> Fixed typo

- hello-kubernetes/README.md
- hello-world/README.md
- hello-world/app.js
Mentioned usage of the Dapr dashboard to get info about the apps running in the k8s quickstart.
Please reference the issue this PR will close: #438
> Mention dashboard in quickstarts (k8s).

- .github/workflows/validate.yaml
> Bump runtime to v1.2.1

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
From time to time, users come to us with feature requests and bug reports for Dapr itself. Adding a comment to help users find the right place so they get triaged properly.
> Update the templates to point people to dapr/dapr for bug/feature requests

- .github/workflows/validate.yaml
> Release 1.3.0-rc.1

- pub-sub/react-form/Dockerfile
Run npm install as part of the container build for pub-sub (rather than doing it at container start).
> Run npm install as part of the container build for pub-sub

- .github/workflows/validate.yaml
- README.md
Bump runtime table for release.
> Update 1.3.0 release

- README.md
> Update latest release links

- .github/workflows/validate.yaml
Automation: Always run quickstarts against latest releases
Avoids having to make PRs to run quickstarts against newest releases.
> Automation: Always run quickstarts against latest releases

- README.md
> Add 1.5.0 to release table

- .github/pull_request_template.md
Add a brief explanation of our automated validation to the default PR template. Also link the user guide for mechanical-markdown.
> Add a PR template with instructions for updating automatic validation

- distributed-calculator/.vscode/tasks.json
- distributed-calculator/README.md
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/python/Dockerfile
- pub-sub/README.md
- pub-sub/deploy/python-subscriber.yaml
- pub-sub/python-subscriber/Dockerfile
- pub-sub/python-subscriber/app.py
replace port 5000 with 5001 to eliminate conflict with Control Center on MacOS
> replace port 5000 with 5001 to eliminate conflict

- .devcontainer/Dockerfile
- README.md
- distributed-calculator/README.md
Get master in sync with release-1.6 ahead of release
> Sync master into release-1.6

- pub_sub/java/http/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- pub_sub/java/sdk/checkout/src/main/java/com/service/CheckoutServiceApplication.java
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
Changing to for loop in place of using Random in while
> using sequence instead of random numbers for orders

- .github/workflows/build.yml
- .github/workflows/validate.yaml
- tutorials/distributed-calculator/README.md
- tutorials/observability/README.md
Added workflow dispatch to trigger the validation and build for the action flow.
> Added workflow dispatch to trigger the validation

- hello-kubernetes/README.md
Signed-off-by: Xin Shi [xshi@microsoft.com](mailto:xshi@microsoft.com)
Quite simple fix in the sample readme
> Fix sample path in readme

- pub_sub/javascript/http/README.md
- pub_sub/javascript/sdk/README.md
> Test fix for pubsub JS

- pub_sub/csharp/http/README.md
Please reference the issue this PR will close: #551
> Fix C# pubsub tests

- pub_sub/python/http/README.md
- pub_sub/python/sdk/README.md
> Fix tests for pubsub python

- pub_sub/java/http/README.md
- pub_sub/java/sdk/README.md
Added tests for java http and sdk pubsub
> Add tests for pubsub java

- .github/workflows/build.yml
- docker.mk
> Add create manifest step for ghcr

- .github/workflows/build.yml
> Login to ghcr before creating manifest

- .github/workflows/build.yml
> Fix GHCR scope issue

- README.md
Signed-off-by: Nick Greenfield <nigreenf@microsoft.com>
Revise readme so it aligns with new quickstarts and tutorials
> Revise readme so it aligns with new quickstarts

- pub_sub/go/http/README.md
- pub_sub/go/http/checkout/app.go
- pub_sub/go/sdk/README.md
- pub_sub/go/sdk/checkout/app.go
> Fixed go tests

- .github/workflows/build.yml
- docker.mk
> run in dapr main repo with dapr ghcr account

- pub_sub/csharp/http/README.md
- pub_sub/csharp/sdk/README.md
- pub_sub/java/http/README.md
- pub_sub/java/sdk/README.md
- pub_sub/javascript/http/README.md
- pub_sub/javascript/sdk/README.md
- pub_sub/python/http/README.md
- pub_sub/python/sdk/README.md
> pubsub test fixes

- .github/workflows/build.yml
> fix the typo in ghcr

- .github/workflows/build.yml
Please reference the issue this PR will close: #568
> Add back PR trigger

- .github/scripts/get_release_version.py
- .github/workflows/build.yml
- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- docker.mk
- tutorials/.devcontainer/Dockerfile
- tutorials/bindings/kafka-non-persistence.yaml
- tutorials/bindings/nodeapp/app.js
- tutorials/bindings/pythonapp/app.py
- tutorials/distributed-calculator/csharp/Controllers/SubtractController.cs
- tutorials/distributed-calculator/csharp/Models/Operands.cs
- tutorials/distributed-calculator/csharp/Program.cs
- tutorials/distributed-calculator/csharp/Startup.cs
- tutorials/distributed-calculator/go/app.go
- tutorials/distributed-calculator/node/app.js
- tutorials/distributed-calculator/python/app.py
- tutorials/docker.mk
- tutorials/hello-kubernetes/node/app.js
- tutorials/hello-kubernetes/python/app.py
- tutorials/hello-world/node/app.js
- tutorials/hello-world/python/app.py
- tutorials/observability/python/app.py
- tutorials/pub-sub/node-subscriber/app.js
- tutorials/pub-sub/python-subscriber/app.py
- tutorials/pub-sub/react-form/client/src/App.test.js
- tutorials/pub-sub/react-form/client/src/MessageForm.js
- tutorials/pub-sub/react-form/client/src/index.js
- tutorials/pub-sub/react-form/client/src/serviceWorker.js
- tutorials/secretstore/node/app.js
Renamed workflows and changes licenses
> Renamed workflows and changed licenses

- README.md
Signed-off-by: Nick Greenfield <nigreenf@microsoft.com>
> Add link to quickstarts docs

- .github/workflows/validate_new_quickstarts_state_management.yaml
- state_management/javascript/http/README.md
- state_management/javascript/http/makefile
- state_management/javascript/sdk/README.md
- state_management/javascript/sdk/makefile
> JS state management tests

- .github/workflows/build.yml
- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- service_invocation/python/http/checkout/app.py
Modified workflow to change Mac OS version
> Changed workflow files to reflect the latest Mac OS

- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
Changed docker version in workflows to avoid docker installation hanging.
> Changed docker installation version

- tutorials/hello-kubernetes/README.md
- tutorials/hello-world/README.md
- tutorials/observability/README.md
Found by Nir Mashkowski
Signed-off-by: Doug Davis <dug@microsoft.com>
> Fix some paths since there's a "tutorial" dir now

- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- tutorials/hello-kubernetes/README.md
- tutorials/hello-kubernetes/deploy/node.yaml
- tutorials/hello-kubernetes/deploy/python.yaml
Modified k8s readme to show API logs. And also using kind to create the cluster for Mac.
> Modified k8s readme to show API logs

- secrets_management/javascript/http/order-processor/index.js
Changed variables in index.js for alignment.
Please reference the issue this PR will close: #652
> Changed variables in index.js

- .github/workflows/validate.yaml
> Testing the worlflow

- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_secrets_management.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- pub_sub/java/http/README.md
- pub_sub/java/sdk/README.md
- service_invocation/java/http/README.md
- service_invocation/java/http/order-processor/src/main/resources/application.properties
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
Java quickstarts auto validate changes
> Java quickstarts auto validate for pubsub, state mgmt and service invo

- .github/workflows/validate_new_quickstarts_state_management.yaml
Changed state management workflow to fix the workflow.
Please reference the issue this PR will close: #686 
> Changed state management workflow

- .github/workflows/validate_new_quickstarts_bindings.yaml
- bindings/csharp/http/README.md
- bindings/csharp/http/batch/program.cs
- bindings/csharp/sdk/README.md
- bindings/csharp/sdk/batch/program.cs
- bindings/go/http/README.md
- bindings/go/http/batch/app.go
- bindings/go/sdk/README.md
- bindings/go/sdk/batch/app.go
- bindings/java/http/README.md
- bindings/java/sdk/README.md
- bindings/javascript/http/README.md
- bindings/javascript/http/batch/index.js
- bindings/javascript/sdk/README.md
- bindings/javascript/sdk/batch/index.js
- bindings/python/http/README.md
- bindings/python/http/batch/app.py
- bindings/python/sdk/README.md
- bindings/python/sdk/batch/app.py
Signed-off-by: Nick Greenfield <nigreenf@microsoft.com>
Change all references of app-id for bindings quickstart to batch-*
> Change all references of app-id in bindings examples to batch-*

- tutorials/bindings/README.md
- tutorials/hello-world/README.md
- tutorials/pub-sub/README.md
- tutorials/secretstore/README.md
Several node apps now use the null coalescing operator '??' which
is not supported until node v14+.
Signed-off-by: Hal Spang <halspang@microsoft.com>
Please reference the issue this PR will close: #706 
> Update Node.js version to support null coalescing

- bindings/db/README.md
Signed-off-by: sunzhaochang <zhchsun1992@gmail.com>
Fix some errors in README for bindings db.
> Update README for bindings db

- bindings/go/http/batch/app.go
- bindings/go/sdk/batch/app.go
Signed-off-by: sunzhaochang <zhchsun1992@gmail.com>
Fix struct tag for json.
> Fix struct tag for json

- .github/workflows/validate_new_quickstarts_bindings.yaml
- tutorials/hello-kubernetes/README.md
Uncommented the workflow for csharp bindings samples. This change will trigger the workflow for csharp bindings examples. 
This PR also includes hello-kubernetes test failures fix.
Please reference the issue this PR will close: #738
> Changes in bindings workflow

- README.md
> Update gitter with Discord

- README.md
Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>
Readme change to follow #787 
#787 
@msfussell
> Update README with link to Workflow quickstart

- CONTRIBUTING.md
Adding instructions for contribution to Quickstart github workflow.
Please reference the issue this PR will close: #815
> Adding conribution instructions for quickstart workflow

- .github/workflows/dapr-bot.yml
Add dapr-bot.yaml to quickstarts. This will help users/devs to assign the issues to themselves by commenting /assign in the issues.
Please reference the issue this PR will close: #814
> Added dapr-bot to quickstart repo

- tutorials/pub-sub/csharp-subscriber/Dockerfile
- tutorials/pub-sub/csharp-subscriber/csharp-subscriber.csproj
Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>
Updates quickstarts/tutorials/pub-sub/csharp-subscriber to use dotnet v7.
> [WIP] v1.11 - Updates quickstarts/tutorials/pub-sub to dotnet v7

- .github/env/global.env
Patching global test env var to test with Dapr Runtime v1.11.0-rc.2
> Patching global test env var to test with Dapr Runtime v1.11.0-rc.2

- .github/env/global.env
Syncing with v1.11-rc2 to enable release and be even with master
> Syncing with v1.11-rc2

- .github/env/global.env
> Hotfix to v1.11-rc.4 Update global.env

- .github/env/global.env
- configuration/go/sdk/README.md
> Revert "    hotfix for 1.11.0-rc.8"

- workflows/csharp/sdk/order-processor/Program.cs
#831 was incomplete since it needs to pass variables to RestoreInventory
passes `make validate`
> Patch/workflow -- fixes #831

- configuration/csharp/http/README.md
- configuration/csharp/http/order-processor/Properties/launchSettings.json
> another port conflict breaking tests

- configuration/csharp/sdk/README.md
Test and code is functionally correct, but timing leads to errors.
> Adding sleep to Configuration test

- .github/env/global.env
Update global.env to 1.11.0-rc.5 for runtime and 1.11.0-rc.1 for CLI
> Upgrading to 1.11.0-rc.5

- .github/env/global.env
Updating QS's to use Rc.6 runtime and Rc.2 CLI
> Updating QS's to use Rc.6 runtime and Rc.2 CLI

- bindings/csharp/http/README.md
- bindings/csharp/http/batch/Debug/net6.0/batch.runtimeconfig.json
- bindings/csharp/sdk/batch/batch.csproj
- configuration/csharp/http/order-processor/Program.csproj
- configuration/csharp/sdk/order-processor/Program.csproj
- pub_sub/csharp/http/checkout/checkout.csproj
- pub_sub/csharp/http/order-processor/order-processor.csproj
- pub_sub/csharp/sdk/checkout/checkout.csproj
- pub_sub/csharp/sdk/order-processor/order-processor.csproj
- secrets_management/csharp/http/order-processor/Program.csproj
- secrets_management/csharp/sdk/order-processor/Program.csproj
- state_management/csharp/http/order-processor/Program.csproj
- state_management/csharp/sdk/order-processor/Program.csproj
- tutorials/pub-sub/csharp-subscriber/csharp-subscriber.csproj
Updated the quickstart projects to reference dotnet SDK v7, from v6.
> Updated dotnet sdk to net7.0

- workflows/python/sdk/README.md
- workflows/python/sdk/order-processor/app.py
Added in flush parameter to print statements for output statements to align with README
* [ x] The quickstart code compiles correctly
* [ x] You've tested new builds of the quickstart if you changed quickstart code
> Adding in flush statements to prints for workflow example

- .github/env/global.env
Updating RC runtime to rc.9 and CLI to rc.3 -- latest.
> Updating RC runtime to RC9

- bindings/components/binding-cron.yaml
- bindings/components/binding-postgres.yaml
- tutorials/observability/README.md
Add best practice `direction` metadata to component yaml files
PR will close: #886 and dapr/docs#3592
> [bindings] add `direction` to component yaml

- tutorials/observability/README.md
Related issues: dapr/docs#3626
> Update links for observability docs update

- .github/env/global.env
Updating runtime for tests to RC5
> Updating runtime for tests to RC5

- .github/env/global.env
Update the dapr cli to use v1.12.0-rc.3 to test & validate the release candidate
https://github.com/dapr/dapr/issues/6899
> update cli to rc.4

- .github/env/global.env
Updating tests to use dapr/dapr RC6
> Updating tests to use dapr/dapr RC6

- bindings/javascript/sdk/batch/package-lock.json
- bindings/javascript/sdk/batch/package.json
- configuration/javascript/sdk/order-processor/package-lock.json
- configuration/javascript/sdk/order-processor/package.json
- cryptography/javascript/sdk/crypto-quickstart/package-lock.json
- cryptography/javascript/sdk/crypto-quickstart/package.json
- pub_sub/javascript/sdk/README.md
- pub_sub/javascript/sdk/checkout/package-lock.json
- pub_sub/javascript/sdk/checkout/package.json
- pub_sub/javascript/sdk/order-processor/package-lock.json
- pub_sub/javascript/sdk/order-processor/package.json
- secrets_management/javascript/sdk/order-processor/package-lock.json
- secrets_management/javascript/sdk/order-processor/package.json
- state_management/javascript/sdk/order-processor/package-lock.json
- state_management/javascript/sdk/order-processor/package.json
> Updating release-1.12 with js-sdk 3.2.0

- .github/env/global.env
updating globals to release-1.13 RC4
Brings tests to latest RC.
> updating globals to release-1.13 RC4

- tutorials/bindings/nodeapp/Dockerfile
- tutorials/distributed-calculator/node/Dockerfile
- tutorials/distributed-calculator/react-calculator/Dockerfile
- tutorials/hello-kubernetes/node/Dockerfile
- tutorials/pub-sub/node-subscriber/Dockerfile
- tutorials/pub-sub/react-form/Dockerfile
- tutorials/secretstore/node/Dockerfile
Now that we've been able to test in prod, I find this image is better for linux/arm
FROM node:20-bullseye
> Updating node based dockerfiles for linux/arm friendly images

- tutorials/observability/README.md
Based on https://github.com/dapr/quickstarts/issues/932 I have made minor issues to the observability tutorial.
#932 
> Refresh the Zipkin observability tutorial

- CODEOWNERS
Updates the codeowners file for the repo
Please reference the issue this PR will close: #N/A
> fix: codeowners update

- actors/csharp/sdk/README.md
- actors/csharp/sdk/client/SmartDevice.Client.csproj
- actors/csharp/sdk/service/SmartDevice.Service.csproj
- bindings/csharp/sdk/batch/batch.csproj
- bindings/csharp/sdk/batch/program.cs
- bindings/python/sdk/batch/requirements.txt
- cryptography/python/sdk/README.md
- pub_sub/python/http/order-processor/requirements.txt
- service_invocation/python/http/order-processor/requirements.txt
- state_management/python/http/order-processor/requirements.txt
- tutorials/pub-sub/python-subscriber/requirements.txt
Merge changes from master to release-1.15 branch
> Merge changes from master to release-1.15 branch

- conversation/python/http/README.md
- conversation/python/http/conversation/app.py
- conversation/python/http/conversation/requirements.txt
- conversation/python/http/dapr.yaml
- conversation/python/http/makefile
Creating Conversation Quickstart for Python - HTTP
Please reference the issue this PR will close: #1108 
> Python Conversation http Quickstart

- README.md
Standardize readme shield badges
Please reference the issue this PR will close: #1023
> Standardize readme shield badges

- .github/env/global.env
Fix python failing tests
https://github.com/dapr/quickstarts/issues/1143
Please reference the issue this PR will close: #1143
> Chore: new rc

- conversation/csharp/http/README.md
- conversation/csharp/sdk/README.md
- conversation/python/http/conversation/app.py
- conversation/python/sdk/README.md
- workflows/go/sdk/README.md
- workflows/go/sdk/order-processor/models.go
- workflows/java/sdk/README.md
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/WorkflowConsoleApp.java
- workflows/javascript/sdk/order-processor/orderProcessingWorkflow.ts
Minor typo fixes
Please reference the issue this PR will close: #1180 
> Fixed a bunch of typos

- README.md
Adds a description for the new workflow tutorials.
> Add workflow tutorial description

- workflows/java/sdk/README.md
> Remove spaces in the workflow README

- jobs/go/sdk/job-service/job-service.go
- workflows/java/sdk/order-processor/pom.xml
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/OrderProcessingWorkflow.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/WorkflowConsoleApp.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/activities/NotifyActivity.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/activities/ProcessPaymentActivity.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/activities/RequestApprovalActivity.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/activities/UpdateInventoryActivity.java
- workflows/java/sdk/order-processor/src/main/java/io/dapr/quickstarts/workflows/activities/VerifyInventoryActivity.java
> Update Dapr Workflows to latest version in Quickstart

- bindings/java/sdk/batch/pom.xml
- configuration/java/sdk/order-processor/pom.xml
- pub_sub/java/sdk/checkout/pom.xml
- pub_sub/java/sdk/order-processor/pom.xml
- secrets_management/java/sdk/order-processor/pom.xml
- state_management/java/sdk/order-processor/pom.xml
- workflows/java/sdk/order-processor/pom.xml
Lastest SDK: https://github.com/dapr/java-sdk/releases/tag/v1.15.0
> chore: Java sdk 1.15.0

- .github/env/global.env
- actors/csharp/sdk/client/SmartDevice.Client.csproj
- actors/csharp/sdk/interfaces/SmartDevice.Interfaces.csproj
- actors/csharp/sdk/service/SmartDevice.Service.csproj
- bindings/csharp/sdk/batch/batch.csproj
- configuration/csharp/sdk/order-processor/Program.csproj
- conversation/csharp/sdk/conversation/Program.csproj
- jobs/csharp/sdk/job-service/Program.cs
- jobs/csharp/sdk/job-service/job-service.csproj
- pub_sub/csharp/sdk/checkout/checkout.csproj
- pub_sub/csharp/sdk/order-processor/order-processor.csproj
- secrets_management/csharp/sdk/order-processor/Program.csproj
- service_invocation/csharp/http/checkout/checkout.csproj
- state_management/csharp/sdk/order-processor/Program.csproj
- tutorials/pub-sub/csharp-subscriber/csharp-subscriber.csproj
- workflows/csharp/sdk/order-processor/WorkflowConsoleApp.csproj
> Chore: RC4 and dotnet rc15

- conversation/go/http/README.md
- conversation/go/http/conversation/conversation.go
Updated the go http quickstart and added tool calling example 
#1214
> Go http tool calling
