- 1.hello-world/README.md
- 1.hello-world/app.js
- 2.hello-kubernetes/README.md
- 2.hello-kubernetes/node/app.js
- 2.hello-kubernetes/python/app.py
- 3.distributed-calculator/README.md
- 3.distributed-calculator/react-calculator/server.js
- 4.pub-sub/node-subscriber/app.js
- 4.pub-sub/react-form/server.js
- 5.bindings/pythonapp/app.py
I've updated samples to use environment variables for the Dapr port, given that the port is configurable in standalone mode and all samples currently hardcoded it to port 3500.
While testing, I also discovered and fixed a bug in the pub-sub sample where the node subscriber microservice was not correctly parsing the incoming messages.
This closes issue #19 
> Reconfigured samples to use env vars for Dapr port instead of hardcoded ports

- 1.hello-world/README.md
fix the state URL in the  GET /orders handler from `daprUrl` (which is not defined in the example, nor in the code) to `stateUrl` (which is consistent with the POST /neworder handler).
* [N/A] Code compiles correctly
* [N/A] Created/updated tests
> fix order state url

- 4.pub-sub/node-subscriber/app.js
Problem: the [recent change](https://github.com/dapr/samples/commit/b5b493008de475820f7821284d56eaabcc1a3e03#diff-ea51cac8927d29371f76d979b3fd3fa8) accepts only `application/json` content-type so that node app doesn't not get the cloud event request from Dapr runtime.
* Revert change to fix pubsub sample.
#79 
> [5.pubsub] revert change to fix pubsub sample

- .github/workflows/build.yml
GitHub Actions CI tries to use secrets variable in the forked repo due to the security reason so when user creates a pr from their fork to original repo, CI will fail to get DOCKER_REGISTRY variable from original repo.
This pr will use the default docker registry in this case.
N/A
> [CI] Set default sample registry in ci

- 1.hello-world/README.md
Remove duplicated word "to" in document of "1.hello-world" sample
#98 
Please reference the issue this PR will close: #98 
> Remove duplicated word "to" in document of "1.hello-world" sample

- 2.hello-kubernetes/README.md
Updated the README to use the correct `docker push` command to publish Docker images to a registry. The previous command `docker publish` does not exist.
Please reference the issue this PR will close: #101 
* [N/A] The sample code compiles correctly
* [N/A] You've tested new builds of the sample if you changed sample code
> 2.hello-kubernetes: Use `docker push` to publish images to a registry

- 5.bindings/README.md
Fix an command option of "kubectl logs" when observing the Python app logs
Fix testclient's incorrect filename
> Fix a command option and testclient's filename

- 5.bindings/README.md
> removing references to EventHubs for binding samples

- 7.middleware/README.md
Fixing the typos in middleware sample readme
> Fixing the typos in middleware sample readme

- 4.pub-sub/react-form/client/src/MessageForm.js
The Pub-Sub sample react-form MessageForm component assigns a dropdown selector value twice, once at the beginning of the element and again at the end, causing linting tools to throw an error when building.
n/a
> remove duplicate messageType assignment in pub-sub sample MessageForm

- 1.hello-world/README.md
On a Ubuntu 18.04 machine the curl command you provide doesn't work since it's missing header data for content-type.
I added the header data for the command in the walkthrough for example 1.
Please reference the issue this PR will close: #194 
> Updating curl command to include Content-type:application/json

- 2.hello-kubernetes/README.md
It adds the warning to README about only default namespace usage in case of  `dapr init --kubernetes` deployment.
Please reference the issue this PR will close: #159 
> Add a warning about non-default namespace usage in Hello Kubernetes sample README

- 1.hello-world/README.md
- 5.bindings/README.md
Default components folder is now located in home dir and created at init time (https://github.com/dapr/cli/pull/354). Modify documentation accordingly
Please reference the issue this PR will close: #227
* [* ] You've updated the sample's README if necessary
> Modify default Components path

- .devcontainer/dapr-setup.sh
- .devcontainer/devcontainer.json
Use dapr samples in visual codespaces #225
> Added files to configure VS codespaces for dapr

- 5.bindings/README.md
Updated commands for pip3 and python3
Removed line for Make sure that you installed helm tiller on your cluster
Removed line ```# move to sample root
kubectl delete -f ./k8s_kafka_testclient.yaml```
Modified to `helm del` command for helm 3 and delete in namespace kafka 
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1619
> Update 5.bindings readme

- 1.hello-world/package.json
- 10.hello-docker-compose/node/package.json
- 2.hello-kubernetes/node/package.json
- 3.distributed-calculator/node/package.json
- 4.pub-sub/node-subscriber/package.json
- 4.pub-sub/react-form/package.json
- 5.bindings/nodeapp/package.json
- 7.middleware/echoapp/package.json
- 9.secretstore/node/package.json
Added private field to package.json files in all samples to stop npm from emitting the warning:
```bash
$ npm install
npm WARN node_server@1.0.0 No repository field.
```
Please reference the issue this PR will close: #196 
> Add private field to stop warning

- 2.hello-kubernetes/README.md
- 2.hello-kubernetes/node/app.js
Modify the hello-k8s sample to expect only injected env vars for Dapr ports. 
Added a simple step in the README to illustrate the same.
This is a **breaking change** to this sample.
Merge only after merging https://github.com/dapr/dapr/pull/1712
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/1637
> modify k8s sample to expect injected env vars

- distributed-calculator/deploy/redis.yaml
dapr components does not connect with redis using double-quoted metadata
Example is using double quotes do not connect on redis.
Please reference the issue this PR will close: #291 
> Remove double quotes from metadata

- hello-world/README.md
The sample link to the Distributed Calculator was using "\\" instead of "/" in the URL
> Fix the Distributed Calculator sample link

- README.md
Asking user to lookup branch name represents significant friction and turns off potential users. This will clone the latest release.
> Copy n paste ready git clone command

- hello-kubernetes/README.md
The documentation reference on the `hello-kubernetes` example is pointing incorrectly to the previous one (`hello-world`). Maybe this is because of a prior modification on the repository, like a rename of a folder, which caused the reference to be obsolete.
https://github.com/dapr/quickstarts/issues/303
> Fix reference to the hello-world example

- hello-world/README.md
Fix POST and invoke command to match `sample.json` otherwise the log entry won't match and may confuse users.
> Fix POST and invoke commands to match sample.json

- hello-kubernetes/python/app.py
- hello-world/app.py
During discovery of https://github.com/dapr/dapr/issues/2114 the Python app received an HTTP error (5xx) but did not print a message. The sample code does already have an error handling block, so it looks like the application was hanging.
This changes the Python app to also print 4xx, 5xx response. Such would make it easier for users to see an issue and report.
> Change hello-{world,kubernetes} Python app to also print HTTP error

- bindings/README.md
Dapr Pods by default doesn't install into the default namespace, but some of the sample output still shows that they are in the default namespace. This PR updates those and also change some `kubectl logs` command to use labels for simplicity.
> Update binding sample

- pub-sub/README.md
- pub-sub/node-subscriber/app.js
- pub-sub/python-subscriber/app.py
Part of a larger effort to address pubsubname REST parameter inconsistencies across the Dapr org repos.
> addresses case inconsistency in pubsubname var

- distributed-calculator/deploy/dotnet-subtractor.yaml
- distributed-calculator/deploy/go-adder.yaml
- distributed-calculator/deploy/node-divider.yaml
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/deploy/react-calculator.yaml
The YAML files in the distributed calculator sample have a redundant dapr.io/config annotation which makes the sidecars crash, as no Configuration is applied in this quickstart.
> Remove appconfig from calculator

- distributed-calculator/README.md
- distributed-calculator/deploy/appconfig.yaml
- distributed-calculator/deploy/dotnet-subtractor.yaml
- distributed-calculator/deploy/go-adder.yaml
- distributed-calculator/deploy/node-divider.yaml
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/deploy/react-calculator.yaml
The distributed calculator quickstart is referenced as an example
in the observability quickstart. This commit adds the appconfig
back into the apps configuration set and introduces the actual
appconfig as well to allow the app to start. This lets users
experience the simplest path for the observability quickstart
while unblocking the calculator.
> Add appconfig back with appropriate yaml config

- distributed-calculator/deploy/appconfig.yaml
- observability/README.md
Set `zipkin.endpointAddress` in Configuration used for observability quickstart. These were missed in https://github.com/dapr/quickstarts/pull/337.
Please reference the issue this PR will close:  #336
> Fix quickstart samples to specify `zipkin.endpointAddress`

- pub-sub/README.md
Use publish-app-id in pubsub quckstart.
Please reference the issue this PR will close: https://github.com/dapr/cli/issues/536
> Use publish-app-id in pubsub quickstart.

- bindings/deploy/node.yaml
- bindings/deploy/python.yaml
- distributed-calculator/deploy/dotnet-subtractor.yaml
- distributed-calculator/deploy/go-adder.yaml
- distributed-calculator/deploy/node-divider.yaml
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/deploy/react-calculator.yaml
- hello-kubernetes/deploy/node.yaml
- hello-kubernetes/deploy/python.yaml
- middleware/deploy/echoapp.yaml
- observability/deploy/python-multiplier.yaml
- pub-sub/deploy/node-subscriber.yaml
- pub-sub/deploy/python-subscriber.yaml
- pub-sub/deploy/react-form.yaml
- secretstore/deploy/node.yaml
Point quickstarts to use 'latest' tag instead of 'edge'
Please reference the issue this PR will close: #346 
> Quickstarts should use latest tag instead of edge (#346)

- distributed-calculator/deploy/redis.yaml
- hello-kubernetes/README.md
- hello-kubernetes/deploy/redis.yaml
* Update hello-kubernetes and distributed-calculator quickstarts to use a redis.yaml that can work out-of-the-box.
> Update hello-kubernetes and distributed-calculator quickstarts to use a redis.yaml that can work out-of-the-box

- hello-world/README.md
Found the upstream root cause for dapr cli being unable to run python when it is installed from the Microsoft Store. The golang exec library does not properly handle App aliases that the Microsoft Store uses. I've updated the hello-world README.md with a better workaround and explanation of the issue.
Please reference the issue this PR will close: #240
> Root cause found for #240. Updated hello-world README.md with better workaround.

- bindings/README.md
Helm kafka install was timing out at the default 60s. Upping the timeout to 120s
Please reference the issue this PR will close: #369
> Increase timeout for helm install of kafka in bindings sample (#369)

- .github/workflows/validate.yaml
- bindings/README.md
- distributed-calculator/csharp/Dockerfile
- distributed-calculator/go/Dockerfile
- distributed-calculator/makefile
- docker.mk
Bump runtime version for validation.
Also, scratch image is not supported in arm64. Use a multiarch image instead.
Turns out, the dotnet build container will not run on arm64, but you can cross compile from the amd64 host and copy the binaries. 
close: #345
> Update runtime to 1.0.0-rc.4

- distributed-calculator/README.md
- observability/README.md
- validate.mk
Mechanical markdown now supports link validation. It will automatically parse links for external domains to ensure that they are available.
```bash
External link validation:
https://docs.docker.com/ Status: 200
https://nodejs.org/en/ Status: 200
https://www.python.org/downloads/ Status: 200
https://www.getpostman.com/ Status: 200
https://docs.dapr.io/getting-started/install-dapr/ Status: 200
https://marketplace.visualstudio.com/items?itemName=humao.rest-client Status: 200
https://marketplace.visualstudio.com/items?itemName=humao.rest-client Status: 200
https://github.com/dapr/quickstarts/issues/240 Status: 200
https://docs.dapr.io/concepts/overview/ Status: 200
https://docs.dapr.io/concepts/ Status: 200
```
We strive to have all PRs being opened based on an issue, where the problem or …
> Add link validation to quickstarts

- hello-kubernetes/README.md
- secretstore/README.md
Dapr init CLI now supports installing to a non-default namespace. Updated READMEs to reflect this.
Please reference the issue this PR will close: #393 
> Update note about installing to non-default namespaces with dapr CLI (#393)

- hello-kubernetes/README.md
Based on some community feedback, the asynchronous nature of kubernetes deployments was causing users to race with the kubernetes deploy steps. This PR adds waits to hello-kubernetes and a brief explanation of the problem. We'll need to do the same for our other kubernetes quickstarts.
ref: #398
> Add wait points to hello-kubernetes for kubernetes deployments

- hello-kubernetes/README.md
"cluser" → "cluster"
Really, it's just one character! 😄
> fix typo in "cluser"

- .github/workflows/validate.yaml
- distributed-calculator/go/go.mod
- distributed-calculator/go/go.sum
Latest go version 1.16.3 no longer supports building without a go.mod file.
> Update to go 1.16.3 for validation tests

- observability/README.md
After you run `dapr init`, the dapr fold should be `$HOME/.dapr/config.yaml`.
#440 
> Correct dapr folder name after dapr init is executed

- README.md
Following the change in go-sdk examples, we need to fix the URL
> Fix URL for go-sdk examples

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
A collision in the name field was causing some of the templates to be not displayed. Also change the about field to make it clear that this queue is for issues related to quickstarts specifically.
> Fix issue template metadata

- pub-sub/react-form/Dockerfile
- pub-sub/react-form/package.json
It wasn't enough just to pre install everything, we actually have to run the full build for the client side to speed up pubsub-react container.
Manually tested on my local machine, this brings container startup. to <2s from 40+
> Do not run any part of the build at container start for pubsub-react

- .devcontainer/devcontainer.json
Replace the deprecated `ms-vscode.go` extension with the currently supported `golang.go` extension in the Dapr devcontainer definition.
Applies the fix for https://github.com/dapr/components-contrib/issues/1022 into the dapr/quickstarts repo as well.
> Update golang extension in devcontainer

- README.md
Remove mentions of Codespaces in beta in README.md since it is no longer in beta.
Follow-up to https://github.com/dapr/docs/issues/1768 in the quickstarts repo
> Update README.md since Codespaces has left Beta

- hello-world/node/app.js
There's some dead and broken code in the hello-world example. Remove it for clarity.
Please reference the issue this PR will close: #333
> The hello-world example does not use DELETE. Removing dead code

- distributed-calculator/react-calculator/Dockerfile
- distributed-calculator/react-calculator/client/package.json
- distributed-calculator/react-calculator/package.json
There is a bug upstream in Create-React-App that doesn't initialize the MiniCssExtractPlugin correctly anymore as it is now requiring Types
> Fix upstream issue in Create-React-App

- distributed-calculator/react-calculator/Dockerfile
Fix client build for react calculator
> Make sure the client is actual built

- .devcontainer/Dockerfile
- README.md
Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>
Update DevContainer base image to fix CodeSpaces and DevContainer issues
The biggest issue is #518 causing Codespace to crash and go into recovery mode. To fix, we change the base image pin in Dockerfile from `universal:1.6.9-focal` to `universal:1-focal` so we get updated 1.x semantic version but stop short of a possibly breaking 2.x release. The 1.6.9 focal image has the issue of running CodeSpaces out of storage during the Docker build (unpack) stages just on line 1 with the base image.  the later 1-focal does not have this issue. 
This has the side effect of fixing #499 since Dapr can properly initialize
Also per #501 we clarify required SKU of GH to see CodeSpaces so more users are successful.
We strive to have all PRs being …
> Update DevContainer base image to fix CodeSpaces and DevContainer issues

- README.md
- distributed-calculator/.vscode/tasks.json
- distributed-calculator/README.md
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/python/Dockerfile
- distributed-calculator/python/app.py
- observability/deploy/python-multiplier.yaml
- observability/python/Dockerfile
- observability/python/app.py
- pub-sub/README.md
- pub-sub/deploy/python-subscriber.yaml
- pub-sub/python-subscriber/Dockerfile
- pub-sub/python-subscriber/app.py
merge release-1.6 branch with master
> Release 1.6

- pub_sub/csharp/http/checkout/Program.cs
- pub_sub/csharp/sdk/checkout/Program.cs
- pub_sub/javascript/http/checkout/index.js
- pub_sub/javascript/sdk/checkout/index.js
- pub_sub/python/http/checkout/app.py
- pub_sub/python/sdk/checkout/app.py
- state_management/csharp/http/order-processor/Program.cs
- state_management/csharp/sdk/order-processor/Program.cs
- state_management/go/http/order-processor/app.go
- state_management/go/sdk/order-processor/app.go
- state_management/javascript/http/order-processor/index.js
- state_management/javascript/sdk/order-processor/index.js
- state_management/python/http/order-processor/app.py
- state_management/python/sdk/order-processor/app.py
Changed a loop structure from "while" to "for"
> Changed loop from while to for

- .github/workflows/build.yml
Remove the check for PR creation event so that docker login happens even when PRs are created
> Remove PR check for docker login

- bindings/README.md
Cleanup bindings test validation to not validate all responses since they aren't always reliable in the start
> Test validation cleanup

- service_invocation/csharp/http/README.md
- service_invocation/go/http/README.md
- service_invocation/go/http/checkout/app.go
- service_invocation/go/http/order-processor/app.go
- service_invocation/javascript/http/README.md
- service_invocation/python/http/README.md
- service_invocation/python/http/checkout/app.py
Added tests for service invocation examples for quickstarts.
Please reference the issue this PR will close: #557 
> Added tests for service invocation

- .github/workflows/build.yml
- docker.mk
Please reference the issue this PR will close: #567
> Publish Quickstart images to ghcr

- bindings/deploy/node.yaml
- bindings/deploy/python.yaml
- distributed-calculator/deploy/dotnet-subtractor.yaml
- distributed-calculator/deploy/go-adder.yaml
- distributed-calculator/deploy/node-divider.yaml
- distributed-calculator/deploy/python-multiplier.yaml
- distributed-calculator/deploy/react-calculator.yaml
- hello-kubernetes/deploy/node.yaml
- hello-kubernetes/deploy/python.yaml
- observability/deploy/python-multiplier.yaml
- pub-sub/deploy/node-subscriber.yaml
- pub-sub/deploy/python-subscriber.yaml
- pub-sub/deploy/react-form.yaml
- secretstore/deploy/node.yaml
> pull from ghcr instead of dockerhub

- .github/workflows/validate_new_quickstarts_state_management.yaml
- service_invocation/go/http/README.md
- state_management/csharp/http/README.md
- state_management/csharp/http/makefile
- state_management/csharp/http/order-processor/Program.csproj
- state_management/csharp/sdk/README.md
- state_management/csharp/sdk/makefile
- state_management/csharp/sdk/order-processor/Program.csproj
- state_management/go/http/README.md
- state_management/go/http/makefile
- state_management/go/http/order-processor/app.go
- state_management/go/sdk/README.md
- state_management/go/sdk/makefile
- state_management/go/sdk/order-processor/app.go
- state_management/java/http/README.md
- state_management/java/http/makefile
- state_management/java/sdk/README.md
- state_management/java/sdk/makefile
- state_management/python/http/README.md
- state_management/python/http/makefile
- state_management/python/sdk/README.md
- state_management/python/sdk/makefile
Added validation tests for state management - Csharp, Go and Python
> Added validation tests for state management

- service_invocation/go/http/README.md
- service_invocation/go/http/order-processor/app.go
Don't marshal the order string because when we do we end up JSON-escaping
things which looks funky and inconsistent with the other samples
Signed-off-by: Doug Davis <dug@microsoft.com>
> Don't marshal the order string

- tutorials/hello-world/README.md
W/o this change the reader might not realize they need to cd into the
'node' dir to see the app.js file that we talk about next.
Also removed some extra whitespace at the end of some lines.
Wasn't sure which branch to base this off of, let me know if you want it moved.
Signed-off-by: Doug Davis <dug@microsoft.com>
> Put reader in 'node' dir

- pub_sub/Commands
- pub_sub/components/pubsub.yaml
- pub_sub/csharp/http/checkout/Program.cs
- pub_sub/csharp/http/order-processor/Program.cs
- pub_sub/csharp/sdk/checkout/Program.cs
- pub_sub/csharp/sdk/order-processor/Program.cs
- pub_sub/go/http/checkout/app.go
- pub_sub/go/http/order-processor/app.go
- pub_sub/go/sdk/checkout/app.go
- pub_sub/go/sdk/order-processor/app.go
- pub_sub/java/http/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- pub_sub/java/http/order-processor/src/main/java/com/service/controller/OrderProcessingServiceController.java
- pub_sub/java/sdk/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- pub_sub/java/sdk/order-processor/src/main/java/com/service/controller/OrderProcessingServiceController.java
- pub_sub/javascript/http/checkout/index.js
- pub_sub/javascript/http/order-processor/index.js
- pub_sub/javascript/sdk/checkout/index.js
- pub_sub/javascript/sdk/order-processor/index.js
- pub_sub/python/http/checkout/app.py
- pub_sub/python/http/order-processor/app.py
- pub_sub/python/sdk/checkout/app.py
- pub_sub/python/sdk/order-processor-fastapi/app.py
- pub_sub/python/sdk/order-processor/app.py
Applying the pub/sub component to Kubernetes results in the following error: 
```
The Component "order_pub_sub" is invalid: metadata.name: Invalid value: "order_pub_sub": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
This PR fixes the component name to be compliant with RFC 1123 .
> Change order_pub_sub to orderpubsub

- pub_sub/go/sdk/order-processor/app.go
- validate.mk
- Update order_processor to listen on -app-port vs. hardcoded port number of 6001. This hardwiring requires the documentation to be updated every time the port changes. Currently, the port used and the documentation are out of sync. By moving to listening on -app-port, order-processor can be run successfully irrespective of the port specified by the user.
- Since quickstarts are for folks bootstrapping on Dapr it is good to automate dependency setup. To run **make** in quickstarts, **mechanical_markdown** is a hard dependency. This is not clearly documented and hence make fails. Updated validate.mk to install **mechanical_markdown** in case it is not already installed.
We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to …
> -app-port for listen port, mm installation

- pub_sub/python/sdk/README.md
- pub_sub/python/sdk/order-processor-fastapi/app.py
- pub_sub/python/sdk/order-processor-fastapi/requirements.txt
- pub_sub/python/sdk/order-processor/requirements.txt
Signed-off-by: Michał Klich <michal@klichx.dev>
I have updated FastAPI example attached to `pub_sub` for Python.
It had not worked correctly.
Sorry, but there is no issue.
> Update Python pub_sub fastapi example

- .github/workflows/validate_new_quickstarts_secrets_management.yaml
- secrets_management/java/http/README.md
- secrets_management/java/http/makefile
- secrets_management/java/http/order-processor/pom.xml
- secrets_management/java/http/order-processor/secrets.json
- secrets_management/java/http/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
- secrets_management/java/sdk/README.md
- secrets_management/java/sdk/makefile
- secrets_management/java/sdk/order-processor/pom.xml
- secrets_management/java/sdk/order-processor/secrets.json
- secrets_management/java/sdk/order-processor/src/main/java/com.service/OrderProcessingServiceApplication.java
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
QuickStart examples for Secret store building block using HTTP client and SDK client
> Java quickstart examples for secret store building block

- tutorials/hello-world/.gitignore
- tutorials/hello-world/.vscode/launch.json
- tutorials/hello-world/.vscode/tasks.json
In the hello-world quickstart, I added folder paths to launch.json for split projects.  The combination of adding in the split project folders for node and python as well as the addition of the VS Code debugging configurations are out of synch and corrected by adding the additional folder paths in launch.json for the hello-world quickstart.
closes #492 
> hello-world - add folder paths to launch for split projects

- tutorials/pub-sub/csharp-subscriber/Dockerfile
Signed-off-by: Arash Rohani <Arash.Rohani@gmail.com>
Updated the C# subscriber docker file to use linux arm image.
Hey @paulyuk It seems that there is one issue with regards to building image for C# in linux arm environment, I found a workaround and made the necessary changes accordingly, would you please merge this with master to test?
> Updated the docker file to use linux arm image

- tutorials/pub-sub/csharp-subscriber/Dockerfile
Reverts dapr/quickstarts#672
As was my worry this hard codes a dockerfile that works for arm, but then breaks AMD:
`image with reference sha256:dbaa06bac17527126cb61a17b4bacf8da3b5c65042ad867cb7492c5755897a03 was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm/v7`
> Revert "Updated the docker file to use linux arm image"

- .gitignore
- pub_sub/go/http/order-processor/app.go
- pub_sub/go/sdk/order-processor/app.go
- pub_sub/javascript/http/order-processor/index.js
- tutorials/bindings/nodeapp/app.js
- tutorials/distributed-calculator/deploy/go-adder.yaml
- tutorials/distributed-calculator/deploy/node-divider.yaml
- tutorials/distributed-calculator/deploy/python-multiplier.yaml
- tutorials/distributed-calculator/go/app.go
- tutorials/distributed-calculator/node/app.js
- tutorials/distributed-calculator/python/app.py
- tutorials/hello-world/node/app.js
- tutorials/observability/deploy/python-multiplier.yaml
- tutorials/observability/python/Dockerfile
- tutorials/observability/python/app.py
Signed-off-by: akhilac1 <chetlapalle.akhila@gmail.com>
1. Added default value for APP_PORT in case it cannot be fetched from environment variables
2. Updated yaml to include addition of environment variable for APP_PORT [ until the dapr.io/app_port annotation issue is fixed #684  ]
3. Default command to run the app in observability quickstart ALWAYS uses port 5000. Updated quickstarts/tutorials/observability/python/Dockerfile to use python3 app.py as launch command and use specified port
Please reference the issue this PR will close: #682 
> #682 APP_PORT not injected into app container

- .devcontainer/Dockerfile
Changes the base image for codespaces from universal:focal (and a pinned version) to universal:latest (which is already cached in codespaces).  This overcomes the issue of the large image pull exceeding the docker layer cache storage limit of the codespace.  
fixes #691 
> Fix CodeSpace failure for quickstarts repo

- .github/workflows/validate_new_quickstarts_state_management.yaml
- state_management/java/http/README.md
- state_management/java/http/order-processor/pom.xml
- state_management/java/http/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
- state_management/java/sdk/README.md
- state_management/java/sdk/order-processor/pom.xml
- state_management/java/sdk/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
- Fix for failing state management java auto validate quickstarts
- Removed Logger and related dependencies as it creates random Id with each log stmt which markdown is not able to validate. Other java examples also follow the same way.
> Fix for failing Auto validate Java examples on State management

- tutorials/pub-sub/README.md
- tutorials/pub-sub/csharp-subscriber/Program.cs
Signed-off-by: Arash Rohani <Arash.Rohani@gmail.com>
Removed the extra space in expected test result to fix the test workflow.
> Removed the extra space in expected test result

- bindings/java/http/batch/pom.xml
- bindings/java/http/batch/src/main/java/com/service/controller/BatchProcessingServiceController.java
- bindings/java/sdk/batch/pom.xml
- bindings/java/sdk/batch/src/main/java/com/service/controller/BatchProcessingServiceController.java
- pub_sub/java/http/checkout/pom.xml
- pub_sub/java/http/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- pub_sub/java/sdk/checkout/pom.xml
- pub_sub/java/sdk/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- pub_sub/java/sdk/order-processor/pom.xml
- secrets_management/java/http/README.md
- secrets_management/java/http/order-processor/pom.xml
- secrets_management/java/http/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
- secrets_management/java/sdk/README.md
- secrets_management/java/sdk/order-processor/pom.xml
- service_invocation/java/http/checkout/pom.xml
- service_invocation/java/http/checkout/src/main/java/com/service/CheckoutServiceApplication.java
- service_invocation/java/http/order-processor/src/main/java/com/service/controller/OrderProcessingServiceController.java
- state_management/java/http/README.md
- state_management/java/http/order-processor/pom.xml
- state_management/java/sdk/README.md
- state_management/java/sdk/order-processor/pom.xml
Signed-off-by: Bilgin Ibryam <bibryam@gmail.com>
- Removed unused imports
- Code style: add space after statements
- Removed unused test code
- Moved Dapr client creation outside of loops
- Update dapr-sdk versions to 1.5
- Added Maven artifact name and description where missing
- Aligned Maven artifact names to camel case
https://github.com/dapr/quickstarts/issues/701
Please reference the issue this PR will close: #_[701]_
> 701: Java quickstarts cleanup:

- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_bindings.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_secrets_management.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- pub_sub/python/http/README.md
- pub_sub/python/http/order-processor/app.py
- pub_sub/python/sdk/README.md
- pub_sub/python/sdk/order-processor/app.py
Changed port numbers for python pubsub examples to resolve the failure of python examples. The workflows were getting stuck on docker installation. This PR has the change to the latest docker action in the workflow and the PR uses the macos 10.15 version in the workflow.
Please reference the issue this PR will close: #724 
> Changed port numbers for python pubsub examples

- pub_sub/csharp/sdk/README.md
Fixes https://github.com/dapr/quickstarts/issues/711
Signed-off-by: Yash Nisar <yashnisar@microsoft.com>
Fixes a broken link in the README
Please reference the issue this PR will close: [#[711]](https://github.com/dapr/quickstarts/issues/711)
> Fixes broken link in the pub/sub README

- secrets_management/java/http/order-processor/pom.xml
- secrets_management/java/sdk/order-processor/pom.xml
- service_invocation/java/http/checkout/pom.xml
- state_management/java/http/order-processor/pom.xml
- state_management/java/sdk/order-processor/pom.xml
Signed-off-by: Ken Chen <chenchaokun@gmail.com>
Change the maven dependency version to make demos compatible with Java 11.
close #719 
> Fix maven dependency incompatible with Java 11

- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_secrets_management.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- pub_sub/csharp/http/README.md
- pub_sub/csharp/sdk/README.md
- pub_sub/csharp/sdk/order-processor/Properties/launchSettings.json
- pub_sub/go/http/README.md
- pub_sub/go/http/order-processor/app.go
- pub_sub/go/sdk/README.md
- pub_sub/go/sdk/order-processor/app.go
- pub_sub/java/http/README.md
- pub_sub/java/sdk/README.md
- pub_sub/javascript/http/README.md
- pub_sub/javascript/sdk/README.md
- pub_sub/javascript/sdk/order-processor/index.js
- pub_sub/python/http/README.md
- pub_sub/python/sdk/README.md
- pub_sub/python/sdk/order-processor/app.py
- service_invocation/csharp/http/makefile
- service_invocation/python/http/README.md
- service_invocation/python/http/order-processor/app.py
- tutorials/pub-sub/README.md
Please reference the issue this PR will close: #730 
> Added parallelism to pubsub workflow

- README.md
- resiliency/service-to-service-resiliency.md
Signed-off-by: Nick Greenfield <nigreenf@microsoft.com>
Add a Resiliency section and link to the QuickStart README
Please reference the issue this PR will close: https://github.com/dapr/quickstarts/issues/751
> Add Resiliency section to QuickStarts README

- .github/workflows/build.yml
- .github/workflows/validate.yaml
- docker.mk
- tutorials/bindings/README.md
- tutorials/bindings/pythonapp/app.py
- tutorials/distributed-calculator/README.md
- tutorials/distributed-calculator/csharp/Dockerfile
- tutorials/distributed-calculator/csharp/Subtract.csproj
- tutorials/hello-kubernetes/README.md
- tutorials/hello-kubernetes/node/app.js
Signed-off-by: Artur Souza <asouza.pro@gmail.com>
Fix tutorial validation and docker build.
Please reference the issue this PR will close: endgame
> Fix tutorial validation and docker build.

- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .gitignore
- service_invocation/csharp/http/README.md
- service_invocation/csharp/http/checkout/checkout.csproj
- service_invocation/csharp/http/dapr.yaml
- service_invocation/csharp/http/order-processor/order-processor.csproj
- service_invocation/go/http/README.md
- service_invocation/go/http/dapr.yaml
- service_invocation/java/http/README.md
- service_invocation/java/http/dapr.yaml
- service_invocation/javascript/http/README.md
- service_invocation/javascript/http/checkout/package-lock.json
- service_invocation/javascript/http/dapr.yaml
- service_invocation/javascript/http/order-processor/package-lock.json
- service_invocation/python/http/README.md
- service_invocation/python/http/dapr.yaml
Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>
- Added multi app run template for service invocation examples
Please reference the issue this PR will close: #777 
> adding multi app run template for service invocation examples

- .github/env/global.env
- .github/workflows/validate.yaml
- .github/workflows/validate_new_quickstarts_bindings.yaml
- .github/workflows/validate_new_quickstarts_configuration.yaml
- .github/workflows/validate_new_quickstarts_pubsub.yaml
- .github/workflows/validate_new_quickstarts_secrets_management.yaml
- .github/workflows/validate_new_quickstarts_service_invo.yaml
- .github/workflows/validate_new_quickstarts_state_management.yaml
- configuration/csharp/sdk/order-processor/Program.cs
- pub_sub/go/http/README.md
- service_invocation/csharp/http/README.md
- service_invocation/go/http/README.md
- service_invocation/java/http/README.md
- service_invocation/java/http/dapr.yaml
- service_invocation/javascript/http/README.md
- service_invocation/javascript/http/dapr.yaml
- service_invocation/python/http/README.md
- service_invocation/python/http/dapr.yaml
Signed-off-by: Artur Souza <asouza.pro@gmail.com>
Pinning dapr version and fixes validations:
+ Fix expected outputs in multiple places
+ Fixed Python runs by pinning to Python 3.10 on MacOS
+ Use Podman on every quickstart that does not refer to Docker CLI commands
+ Limit workflows to 30min or less to avoid taking over worker for hours/days
+ Use GHCR instead of Docker Hub everywhere
+ Pin DAPR runtime and CLI because automation was picking the latest, so a hotfix after an RC did mess up with the validation for 1.10 release
+ Removed unnecessary sleep in `dapr run -f` scenario
+ Fixed reference to removed confing.yaml since Resiliency is on by default now. …
> Pinning dapr version and fixes multiple validations

- pub_sub/csharp/sdk/README.md
- pub_sub/csharp/sdk/order-processor/Properties/launchSettings.json
- service_invocation/csharp/http/README.md
- service_invocation/csharp/http/dapr.yaml
- service_invocation/csharp/http/order-processor/Properties/launchSettings.json
In the C# service invocation quickstart order-processor service, changed the port from `7006` to `7001` to align with the [quickstart instructions](https://docs.dapr.io/getting-started/quickstarts/serviceinvocation-quickstart/#step-3-run-order-processor-service).
PR is in response to issue: https://github.com/dapr/docs/issues/3296
> adjust service_invocation/csharp order-processor port

- workflows/csharp/sdk/order-processor/Program.cs
- workflows/csharp/sdk/order-processor/WorkflowConsoleApp.csproj
This PR contains updates for the workflow quickstart to make it compatible with v1.11, which has many breaking changes since v1.10. Some quick notes about the changes that impact this existing quickstart:
- We've removed the need for the `DaprWorkflowClient` class. Instead, we can just use `DaprClient` as originally intended.
- Looping and sleeping have been replaced with first-class "WaitForWorkflowXXX" methods on the DaprClient.
This PR depends on a v1.11 .NET SDK to be available on nuget.org. It won't run without this.
Resolves https://github.com/dapr/quickstarts/issues/830.
cc @msfussell @hhunter-ms @nyemade-uversky @RyanLettieri @halspang 
> [Workflow] Updates for v1.11

- .github/workflows/build.yml
This fixes Build action
Build action is failing because the create docker manifest step actually tries to access Docker container registry first, and that requires a login.  To fix we move the Docker login step up before. 
> Fixing Docker error in Build github action

- .github/workflows/validate_csharp_quicstarts.yaml
The podman tests are failing so we'll we can find a better approach
> Disable mac tests temporarily

- bindings/csharp/http/README.md
- bindings/csharp/http/batch/Properties/launchSettings.json
- configuration/csharp/http/README.md
- configuration/csharp/http/order-processor/Properties/launchSettings.json
- configuration/csharp/sdk/README.md
- pub_sub/csharp/http/README.md
- pub_sub/csharp/http/order-processor/Properties/launchSettings.json
- pub_sub/csharp/sdk/README.md
- pub_sub/csharp/sdk/order-processor/Properties/launchSettings.json
C# projects often overlapped on ports 7001 and 7002 causing collisions during automated testing.
> Unique ports to fix C# tests collisions

- tutorials/bindings/README.md
Github actions have been failing for tutorials due to change in logging. This has been fixed by changing the expected logs in markdown file.
Please reference the issue this PR will close: #858
> Fixing tutorials workflow

- .github/workflows/validate_csharp_quicstarts.yaml
- .github/workflows/validate_go_quickstarts.yaml
- .github/workflows/validate_java_quicstarts.yaml
- .github/workflows/validate_javascript_quicstarts.yaml
- .github/workflows/validate_python_quicstarts.yaml
Latest version of Podman seems to be unstable where it times out more often, so pinning the podman version to 4.4.4, which is more reliable as of now..
Please reference the issue this PR will close: #862
> Pinning podman to 4.4.4 version

- bindings/python/sdk/batch/requirements.txt
- configuration/python/sdk/order-processor/requirements.txt
- pub_sub/python/sdk/checkout/requirements.txt
- pub_sub/python/sdk/order-processor/requirements.txt
- secrets_management/python/sdk/order-processor/requirements.txt
- state_management/python/sdk/order-processor/requirements.txt
This is a mechanism to test with "RC" level changes before the official dapr module releases on PyPi.
I have tested locally with `make validate`
@msfussell @berndverst
> Updating python quickstarts to use `dapr-dev` module

- tutorials/pub-sub/README.md
Added commands to see the details of events in the redis stream
Please reference the issue this PR will close: #668 
> Show insights into the Cloud Events in the Pub/Sub tutorial

- tutorials/distributed-calculator/README.md
Removing broken link to user profile, and keeping link to archived repo
Fixes this recurring test failure:
https://github.com/dapr/quickstarts/actions/runs/5256605105/jobs/9498167540#step:22:872
> Tutorials test fix - broken link

- cryptography/javascript/sdk/README.md
- cryptography/javascript/sdk/crypto-quickstart/index.mjs
- cryptography/javascript/sdk/crypto-quickstart/package-lock.json
- cryptography/javascript/sdk/crypto-quickstart/package.json
2 fixes for JS crypto quickstart:
1. Updated the JS SDK to 3.1.1 to fix an issue that was detected in the tests in this repo (https://github.com/dapr/js-sdk/pull/503)
1. Fixed 2 typos in output
> Fixups for JS crypto quickstart

- workflows/python/sdk/README.md
- workflows/python/sdk/order-processor/app.py
Changed item purchase to 10 cars instead of 11 for better parity between language sdks.
> Made python quickstart README.md match the .NET purchasing example

- service_invocation/go/http/order-processor/app.go
Update the commonts with correct port
Please reference the issue this PR will close: #899
> Update comments with correct port

- pub_sub/go/http/checkout/app.go
- pub_sub/go/sdk/checkout/app.go
The current implementation calls `time.Sleep(1000)` with untyped literal `1000`, which is interpreted as 1000 nanoseconds, or 1 millisecond.
This commit changes the sleep duration to proper typed constant `time.Second`, which corresponds to the sleep time of other language examples.
This issue will close #890.
I have completed all the tasks:
> pub_sub: go: set publisher sleep to 1 second

- tutorials/distributed-calculator/README.md
As we use the `go run app.go` command, we do not need to prebuild (i.e `go build .`). 
No code change.
N/A
> Go build not needed for `go run`

- pub_sub/python/sdk/README.md
- Correct the app port in README to make it works again.
- In particular, this fix makes the fastapi example works again.
- The flask example previously still works, due to its code fetchs the app port via the env variable.
N/A
> Update Python pub_sub sdk example

- .github/workflows/validate_python_quicstarts.yaml
- pub_sub/csharp/http/README.md
- pub_sub/csharp/sdk/README.md
Patching tests to pass (C# timing, Python uvicorn)
- C# chooses earlier item to not be in race condition with timeout
- Python pip3 installs fastapi and uvicorn and sets path, so uvicorn is found
> Patching tests to pass (C# timing, Python uvicorn)

- .github/env/global.env
- .github/workflows/validate.yaml
- configuration/go/sdk/README.md
- configuration/go/sdk/order-processor/app.go
Update dapr runtime to use v1.12.0-rc.3 && dapr cli to use v1.12.0-rc.1 to test & validate the release candidate
https://github.com/dapr/dapr/issues/6899
> update dapr runtime to use v1.12.0-rc.1

- pub_sub/java/sdk/README.md
- service_invocation/csharp/http/README.md
- tutorials/bindings/README.md
Setting Kafka to earlier version.
> setting version for kafka

- actors/csharp/sdk/client/SmartDevice.Client.csproj
- actors/csharp/sdk/interfaces/SmartDevice.Interfaces.csproj
- actors/csharp/sdk/service/SmartDevice.Service.csproj
- bindings/csharp/sdk/batch/batch.csproj
- configuration/csharp/sdk/order-processor/Program.csproj
- pub_sub/csharp/sdk/checkout/checkout.csproj
- pub_sub/csharp/sdk/order-processor/order-processor.csproj
- secrets_management/csharp/sdk/order-processor/Program.csproj
- state_management/csharp/sdk/order-processor/Program.csproj
- tutorials/pub-sub/csharp-subscriber/csharp-subscriber.csproj
- workflows/csharp/sdk/order-processor/WorkflowConsoleApp.csproj
Bumping dotnet sdk to latest RC
> Bump csharp sdk to latest RC

- pub_sub/go/http/README.md
- pub_sub/go/http/dapr.yaml
…issue
The timing of tests leads to conflict on port 6003
Current failed tests for Go
> Fixes port 6003 conflict between Go Pub-sub and Go bindings.  

- .github/env/global.env
- .github/workflows/validate.yaml
- .gitignore
- tutorials/distributed-calculator/README.md
- tutorials/hello-kubernetes/README.md
- tutorials/hello-kubernetes/dapr.yaml
- tutorials/validate.mk
> add hello-kubernetes multi-app run k8s template

- .github/env/global.env
- bindings/go/sdk/batch/go.mod
- bindings/go/sdk/batch/go.sum
- bindings/java/sdk/batch/pom.xml
- configuration/go/sdk/order-processor/go.mod
- configuration/go/sdk/order-processor/go.sum
- configuration/java/sdk/order-processor/pom.xml
- cryptography/go/sdk/crypto-quickstart/go.mod
- cryptography/go/sdk/crypto-quickstart/go.sum
- pub_sub/go/sdk/checkout/go.mod
- pub_sub/go/sdk/checkout/go.sum
- pub_sub/go/sdk/order-processor/go.mod
- pub_sub/go/sdk/order-processor/go.sum
- pub_sub/java/sdk/checkout/pom.xml
- pub_sub/java/sdk/order-processor/pom.xml
- secrets_management/go/sdk/order-processor/go.mod
- secrets_management/go/sdk/order-processor/go.sum
- secrets_management/java/sdk/order-processor/pom.xml
- state_management/go/sdk/order-processor/go.mod
- state_management/go/sdk/order-processor/go.sum
- state_management/java/sdk/order-processor/pom.xml
- workflows/java/sdk/order-processor/pom.xml
Changed DAPR & CLI version to point to latest released version, also modified Go & Java SDK version to latest released version.
Please reference the issue this PR will close: endgame
> Sdkversionchange

- .github/env/global.env
Updates all CI/CD testing in the release branch to use updated 1.13 RC runtime release.
Needed for testing. 
https://github.com/dapr/dapr/actions/runs/7802473423
> Updating CI/CD actions to use release-1.13 of dapr/dapr runtime

- .github/env/global.env
- bindings/components/binding-cron.yaml
- bindings/components/binding-postgres.yaml
- state_management/csharp/http/README.md
- state_management/csharp/sdk/README.md
- state_management/go/http/README.md
- state_management/go/sdk/README.md
- state_management/javascript/sdk/README.md
Tests now fail in state management CI/CD because of the final `dapr stop` on the single service.  in 1.12.0 the service was still available to stop by the time this step ran.  Now, the service is already gone, so stop fails.  The fix is to keep the stop in the readme, but remove it from the test workflow which will run it in CI.  
> Fix tests broken by timing change

- .github/env/global.env
- bindings/components/binding-cron.yaml
- bindings/components/binding-postgres.yaml
- state_management/csharp/http/README.md
- state_management/csharp/sdk/README.md
- state_management/go/http/README.md
- state_management/go/sdk/README.md
- state_management/javascript/sdk/README.md
> Revert "Fix tests broken by timing change"

- .github/env/global.env
- bindings/components/binding-cron.yaml
- bindings/components/binding-postgres.yaml
- state_management/csharp/http/README.md
- state_management/csharp/sdk/README.md
- state_management/go/http/README.md
- state_management/go/sdk/README.md
- state_management/javascript/sdk/README.md
Enables 1.13 RC release
- Updates CI/CD actions to use 1.13 RC2 release
- Tests pass using timing fixes for `dapr stop` calls
- Applies workaround for binding namespace bug 
- rebaselines PR to merge with dapr/quickstarts:release-1.13 branch, update to #979 
> Release 1.13

- actors/csharp/sdk/service/SmokeDetectorActor.cs
The previous language used in the description in this quickstart was confusing and has spawned at least two questions about it that I've seen in the Discord channel. Updated to reflect that while changes to the state are made to the cache on a per-actor basis, but that an explicit call to `SaveStateAsync` is required to persist the state changes to the underlying actor state store.
I didn't make any code changes - just updated a comment in a method.
None: Question raised in Discord.
> Clarified actor state persistence description

- workflows/csharp/sdk/order-processor/Program.cs
please refer to issue [#1205](https://github.com/dapr/dotnet-sdk/issues/1205) in dapr/dotnet-sdk.
> use daprWorkflowClient instead of daprClient in workflow sample

- .github/workflows/dapr-bot.yml
Starting V5 of Github actions, there is a change in the rest end points.  github.issues.** has changed to github.rest.issues**; hence dapr bot is not functioning for some of these actions.  
Reference: https://github.com/actions/github-script#breaking-changes-in-v5
Please reference the issue this PR will close: #966 
> Fix the DAPR bot script addressing this issue #966

- .github/env/global.env
- .github/workflows/validate_csharp_quicstarts.yaml
- .gitignore
- actors/csharp/sdk/README.md
- actors/csharp/sdk/client/SmartDevice.Client.csproj
- actors/csharp/sdk/interfaces/SmartDevice.Interfaces.csproj
- actors/csharp/sdk/sdk.sln
- actors/csharp/sdk/service/SmartDevice.Service.csproj
- bindings/csharp/http/batch/batch.csproj
- bindings/csharp/sdk/batch/batch.csproj
- configuration/csharp/http/order-processor/Program.csproj
- configuration/csharp/sdk/order-processor/Program.csproj
- pub_sub/csharp/http/checkout/checkout.csproj
- pub_sub/csharp/http/order-processor/order-processor.csproj
- pub_sub/csharp/sdk/checkout/checkout.csproj
- pub_sub/csharp/sdk/order-processor/order-processor.csproj
- secrets_management/csharp/http/order-processor/Program.csproj
- secrets_management/csharp/sdk/order-processor/Program.csproj
- service_invocation/csharp/http/checkout/checkout.csproj
- service_invocation/csharp/http/order-processor/order-processor.csproj
- state_management/csharp/http/order-processor/Program.csproj
- state_management/csharp/sdk/order-processor/Program.csproj
- tutorials/pub-sub/csharp-subscriber/csharp-subscriber.csproj
- workflows/csharp/sdk/order-processor/WorkflowConsoleApp.csproj
Converted quickstart projects to use .Net 8 runtime and SDK in all C# projects.
Please reference the issue this PR will close: #980
> Convert to net8 on release 1.13

- .github/env/global.env
- bindings/components/binding-cron.yaml
- bindings/components/binding-postgres.yaml
Updating to RC6 which has fix to #982
Restoring `quickstarts` namespaces in components
Please reference the issue this PR will close: #982 and https://github.com/dapr/dapr/issues/7523
> Updating to RC6 which has fix to #982

- state_management/go/sdk/order-processor/go.mod
- workflows/go/sdk/order-processor/go.mod
What happened is the go tools inserted toolchain go1.22.0 into go.mod, and that forced the automated test to midstream download go.1.22.0 (because they are based on go 1.21.0) and that is what munged the text output.  
This hint was deep in the logs on line 937 where you see `downloading go1.22.0`.  
https://github.com/dapr/quickstarts/actions/runs/8089746951/job/22106150891#step:12:928
```
== APP - order-processor == go: downloading go1.22.0 (linux/amd64)
```
> Test fix: Removing `toolchain go*` lines that cause midstream downloads

- tutorials/hello-kubernetes/node/app.js
- tutorials/hello-kubernetes/python/app.py
I've updated the examples to use the DAPR_HTTP_ENDPOINT and DAPR_GRPC_ENDPOINT environment variables that are used by the SDKs. If DAPR_HTTP_PORT needs to be also supported I will need some help to validate the code. 
I am not sure how images are created for these applications, help is appreciated to validate these changes.
Please reference the issue this PR will close: #1029 
> Updating `hello-kubernetes` quickstart to support Endpoint env vars

- configuration/python/sdk/README.md
- configuration/python/sdk/order-processor/app.py
Test failures can happen running tests on 1.13 -> 1.14 because test relied on implicit ToString instead of inspecting .value off of the configuration item.  Also ensure print consistently handles string interpolation.  
Thank you @berndverst for educating me here.
#1050 
> Fixes Python test failure on Configuration API quickstart

- .github/env/global.env
Changing Dapr runtime version to 1.13.5 to support test efforts
Let's see if this helps with #1047 
> Changing Dapr runtime version to 1.13.5 to support test efforts

- bindings/java/http/batch/pom.xml
- bindings/java/sdk/batch/pom.xml
- configuration/java/http/README.md
- configuration/java/http/order-processor/pom.xml
- configuration/java/sdk/README.md
- configuration/java/sdk/order-processor/pom.xml
- configuration/java/sdk/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
- pub_sub/java/http/README.md
- pub_sub/java/http/checkout/pom.xml
- pub_sub/java/http/order-processor/pom.xml
- pub_sub/java/sdk/README.md
- pub_sub/java/sdk/checkout/pom.xml
- pub_sub/java/sdk/order-processor/pom.xml
- secrets_management/java/http/order-processor/pom.xml
- secrets_management/java/sdk/order-processor/pom.xml
- service_invocation/java/http/README.md
- service_invocation/java/http/checkout/pom.xml
- service_invocation/java/http/order-processor/pom.xml
- state_management/java/http/README.md
- state_management/java/http/order-processor/pom.xml
- state_management/java/sdk/README.md
- state_management/java/sdk/order-processor/pom.xml
- workflows/java/sdk/order-processor/pom.xml
feat: bumped up dependencies for Java Quickstarts , Springboot 2 is out of support so i have changes all the projects to use latest springboot 3 version available on the day of raising PR. I have tested all projects locally and github actions as well.
docs: Updated read me files to use Java 17 as baseline
Signed-off-by: amardeep2006 <amardeep2006@gmail.com>
Upgraded Java Quickstarts to latest versions of dependencies.
https://github.com/dapr/quickstarts/issues/1042
Please make sure you've completed the relevant tasks for this PR, out of the following …
> feat: upgraded springboot to 3.3.1 and bumped up other dependencies

- tutorials/pub-sub/csharp-subscriber/Dockerfile
Update tutorials pub-sub csharp-subscriber image to dotnet 8.0
Please reference the issue this PR will close: #1000 
> Update tutorials pub-sub csharp-subscriber image to dotnet 8.0

- pub_sub/javascript/http/checkout/package-lock.json
- pub_sub/javascript/http/checkout/package.json
- pub_sub/javascript/http/order-processor/package-lock.json
- pub_sub/javascript/sdk/checkout/package-lock.json
- pub_sub/javascript/sdk/order-processor/package-lock.json
`npm audit fix`
and `npm audit fix --force` to upgrade `axios`
Please reference the issue this PR will close: #1054 
> fix: pub_sub javascript npm audit issues

- .github/holopin.yml
The `yaml` file to award contribution badges has been updated such that each contributor can be awarded a Quickstarts badge for their contribution to this repo.
This PR fixes #1004 
Please make sure you've  completed the relevant tasks for this PR, out of the following list:
> Update holopin.yml to award Quickstarts badge to contributors

- tutorials/distributed-calculator/go/Dockerfile
Go example was using old Go image (1.15) for newer Go in `go.mod` 1.19.
Updated the image version and included `go.mod` and `go.sum`
> Fix distributed calculator tutorial Go docker build

- .gitignore
- tutorials/distributed-calculator/csharp/Dockerfile
- tutorials/distributed-calculator/node/Dockerfile
- tutorials/distributed-calculator/python/Dockerfile
- tutorials/distributed-calculator/react-calculator/Dockerfile
- tutorials/hello-kubernetes/node/Dockerfile
- tutorials/hello-kubernetes/python/Dockerfile
- tutorials/observability/python/Dockerfile
- tutorials/pub-sub/csharp-subscriber/Dockerfile
- tutorials/pub-sub/node-subscriber/Dockerfile
- tutorials/pub-sub/python-subscriber/Dockerfile
- tutorials/pub-sub/react-form/Dockerfile
Updating tools chains in dockerfiles to:
- use latest of each language stack's SDK that is compatible with app
- multi stage build in .net for performance and size
- build and test clean with `make build` in each tutorial folder
- leveraged by build.yaml github action workflow
This is a companion fix to #1058 for the other languages
> Updating dockerfiles used in Tutorial make build (C#,Python,Node,ReactClient)

- tutorials/pub-sub/csharp-subscriber/Dockerfile
Fixing dockerfile for Tutorial pubsub C# to be truly multi-arch.  Was hard coded to arm64 (like apple silicon test machine)
Fixes this test failure.
https://github.com/dapr/quickstarts/actions/runs/10081924109/job/27880177990#step:8:847
Tested and run in docker.
> Fixing dockerfile for Tutorial pubsub C# to be truly multi-arch

- .github/workflows/validate_tutorials.yaml
- tutorials/hello-kubernetes/README.md
- tutorials/hello-kubernetes/dapr.yaml
- tutorials/hello-kubernetes/resources/resiliency.yaml
- tutorials/observability/README.md
- Renames the tutorials validation workflow to `validate_tutorials.yaml`
- Bumps kind & kubernetes to more recent, supported versions and image tag.
- Defines a global resiliency policy
- Updates dapr returned endpoints
- Adds some timings to allow for metrics to propagate before validation takes place
CLI related issue: [1436](https://github.com/dapr/cli/issues/1436)
> fix: validate_tutorials

- configuration/javascript/sdk/order-processor/package-lock.json
- configuration/javascript/sdk/order-processor/package.json
- cryptography/javascript/sdk/crypto-quickstart/package-lock.json
- cryptography/javascript/sdk/crypto-quickstart/package.json
I debugged and found that the issue happened as, in isStarted func of sidecar.js, we are using GetMetadata API which had an Empty proto as request, while that was updated and wrapped inside a GetMetadataRequest().
But, I also found that it is already being used by v3.3.1 - so referred that and issue got resolved.
refer this run for validation: https://github.com/DeepanshuA/quickstarts/actions/runs/10109780799/job/27958376419
Please reference the issue this PR will close: #1047 
> Fix for Quickstart Failure

- configuration/javascript/sdk/order-processor/package-lock.json
- cryptography/javascript/sdk/crypto-quickstart/package-lock.json
- tutorials/observability/README.md
We were missing master change for observability, and need to fix merge conflicts.
> Syncing new PRs release-1.14

- pub_sub/javascript/http/order-processor/package.json
pub_sub quick start projects crashes with:
`== APP - order-processor-http == Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'body-parser' `
The PR adds body-parser version ^1.19.0 - the newest one used in other quick start projects
No related issue created
> add missing body-parser package to js pub_sub order-processor

- bindings/csharp/http/batch/program.cs
- bindings/csharp/sdk/batch/program.cs
Use `InvariantCulture` to fix localization.
Or else you get (on non-US): 
```
== APP == insert into orders (orderid, customer, price) values (1, 'John Smith', 100,32);
== APP == fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
== APP ==       An unhandled exception has occurred while executing the request.
== APP ==       Dapr.DaprException: Binding operation failed: the Dapr endpoint indicated a failure. See InnerException for details.
== APP ==        ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="error invoking output binding sqldb: error executing query: ERROR: INSERT has more expressions than target columns (SQLSTATE 42601)")`
```
> InvariantCulture to fix localization

- bindings/csharp/http/README.md
- bindings/csharp/sdk/README.md
- bindings/go/http/README.md
- bindings/go/sdk/README.md
- bindings/java/http/README.md
- bindings/java/sdk/README.md
- bindings/javascript/http/README.md
- bindings/javascript/sdk/README.md
- bindings/python/http/README.md
- bindings/python/sdk/README.md
- tutorials/bindings/README.md
Fix workflows to use `docker compose` instead of `docker-compose`
Please reference the issue this PR will close: n/a
> Fix workflows to use `docker compose` instead of `docker-compose`

- workflows/python/sdk/README.md
- workflows/python/sdk/order-processor/app.py
- workflows/python/sdk/order-processor/workflow.py
Notice the python quickstart example is outdated, so update it to use `DaprWorkflowClient` instead of `DaprClient`, same as here in python-sdk repo https://github.com/dapr/python-sdk/blob/main/examples/workflow/child_workflow.py
Checked mm.py and verify it works
https://github.com/dapr/quickstarts/issues/1119
> refactor: update python workflow example with daprWorkflowClient

- cryptography/python/sdk/README.md
- cryptography/python/sdk/crypto-quickstart/.gitignore
- cryptography/python/sdk/crypto-quickstart/app.py
- cryptography/python/sdk/crypto-quickstart/requirements.txt
- cryptography/python/sdk/makefile
Based on the implementation in this [PR](https://github.com/dapr/python-sdk/pull/729), add python-sdk in cryptography
Please reference the issue this PR will close: #1052 
> add python-sdk in cryptography

- actors/csharp/sdk/README.md
- actors/csharp/sdk/client/SmartDevice.Client.csproj
- actors/csharp/sdk/service/SmartDevice.Service.csproj
.NET 7 is **NOT** a supported target. Updated the README and updated the Dapr packages to 1.15.0-rc02.
N/A - part of [1.15 endgame](https://github.com/dapr/dapr/issues/8313)
> Update Dapr Actors Quickstart - .NET

- jobs/csharp/http/README.md
- jobs/csharp/http/dapr.yaml
- jobs/csharp/http/job-scheduler/Program.cs
- jobs/csharp/http/job-scheduler/jobs-scheduler.csproj
- jobs/csharp/http/job-service/Program.cs
- jobs/csharp/http/job-service/Properties/launchSettings.json
- jobs/csharp/http/job-service/appsettings.Development.json
- jobs/csharp/http/job-service/appsettings.json
- jobs/csharp/http/job-service/job-service.csproj
- jobs/csharp/http/makefile
- jobs/go/http/README.md
HTTP csharp jobs quickstart, plus a few edits to the Go HTTP quickstart readme for verbiage updates.
Issue this PR will close: https://github.com/dapr/quickstarts/issues/1113
> HTTP csharp jobs quickstart

- tutorials/hello-world/.vscode/launch.json
When trying to debug helloworld app in vscode I noticed there is no terminal for node app which makes debugging not easy. This PR fixes this issue
#1124 
> helloworld: add terminal to node app for vscode

- conversation/csharp/http/README.md
- conversation/csharp/http/conversation/Program.cs
- conversation/csharp/http/conversation/Program.csproj
- conversation/csharp/http/dapr.yaml
- conversation/csharp/http/makefile
- conversation/csharp/sdk/README.md
- conversation/csharp/sdk/conversation/Program.cs
- conversation/csharp/sdk/conversation/Program.csproj
- conversation/csharp/sdk/dapr.yaml
- conversation/csharp/sdk/makefile
- conversation/go/http/README.md
- Csharp conversation API quickstarts
- Rewrote @WhitWaldo's PR: https://github.com/dapr/quickstarts/pull/1133 to keep the simple for quickstarts and then we can move his Anthropic example to Dotnet SDK repo
- Small readme updates to golang
Please reference the issue this PR will close: #1103 #1105
> Csharp conversation API quickstarts

- conversation/javascript/http/README.md
- conversation/javascript/http/conversation/index.js
- conversation/javascript/http/conversation/package-lock.json
- conversation/javascript/http/conversation/package.json
- conversation/javascript/http/dapr.yaml
- conversation/javascript/http/makefile
Added the missing quickstart for how to use the Dapr Conversation with Javascript through the standard HTTP `fetch`.
https://github.com/dapr/quickstarts/issues/1107
> Conversation JS HTTP Quickstart

- jobs/csharp/http/job-scheduler/Program.cs
- jobs/go/http/job-scheduler/job-scheduler.go
- jobs/javascript/http/job-scheduler/index.js
- jobs/python/http/README.md
- jobs/python/http/job-scheduler/app.py
Renamed `schedulerDaprHttpPort` to `jobServiceDaprHttpPort` since this port (6280) belongs to the job-service's Dapr sidecar that the scheduler connects to, not the scheduler itself. This makes the code clearer about the relationships.
Also note the env vars for the python example.
> Jobs API Clarity: Rename schedulerDaprHttpPort -> jobServiceDaprHttpPort

- tutorials/workflow/csharp/child-workflows/ChildWorkflows/ChildWorkflows.csproj
- tutorials/workflow/csharp/combined-patterns/WorkflowApp/WorkflowApp.csproj
- tutorials/workflow/csharp/external-system-interaction/ExternalEvents/ExternalEvents.csproj
- tutorials/workflow/csharp/fan-out-fan-in/FanOutFanIn/FanOutFanIn.csproj
- tutorials/workflow/csharp/fundamentals/Basic/Basic.csproj
- tutorials/workflow/csharp/monitor-pattern/Monitor/Monitor.csproj
- tutorials/workflow/csharp/resiliency-and-compensation/ResiliencyAndCompensation/ResiliencyAndCompensation.csproj
- tutorials/workflow/csharp/task-chaining/TaskChaining/TaskChaining.csproj
- tutorials/workflow/csharp/workflow-management/WorkflowManagement/WorkflowManagement.csproj
- workflows/csharp/sdk/order-processor/WorkflowConsoleApp.csproj
Update the .NET SDK to the 1.15.4 to prevent worfklow issues due to grpc connections. [Issue 1523](https://github.com/dapr/dotnet-sdk/pull/1523).
> Update Dapr.Workflow to 1.15.4

- bindings/java/sdk/batch/pom.xml
- configuration/java/sdk/order-processor/pom.xml
- pub_sub/java/sdk/checkout/pom.xml
- pub_sub/java/sdk/order-processor/pom.xml
- secrets_management/java/sdk/order-processor/pom.xml
- state_management/java/sdk/order-processor/pom.xml
- workflows/java/sdk/order-processor/pom.xml
[Per maven central, we are a bit behind on the java version in the quickstarts repo -- updated to latest](https://repo1.maven.org/maven2/io/dapr/dapr-sdk/)
> update java to latest rc

- conversation/javascript/http/README.md
- conversation/javascript/http/conversation/index.js
- Changed the request URL to use the new API on `v1.0-alpha2` 
- Updated the example to work with the new protos
- Extended the example to include tool-calling
https://github.com/dapr/quickstarts/issues/1207
https://github.com/dapr/quickstarts/issues/1210
> Updated request url to alpha2 and updated quickstart to support toolcalling

- tutorials/distributed-calculator/csharp/Dockerfile
build pipeline failing due to version mismatch
> Update Dockerfile to use .NET SDK and runtime version 8.0

- conversation/csharp/http/conversation/Program.cs
- Fix for the reported bug #1250 
- Also removed name in the request body as component name should come from the URL
#1250 1250
> Fix #1250 KeyNotFoundException in conversation quickstart tool calling
